### ISSUE TITLE
UI texts and ticks are not visible in Linux (Debain)

### ISSUE THREAD

**Issue by cgvirus** [darbyjohnston/DJV#1]
Hello, thanks for the updates on this great piece of software. Just to let you know, In 1.2.2 UI texts and ticks are not visible. In Debain Buster/Sid.

**Comment by darbyjohnston** [comment]
Hi,

Thanks for the bug report! I'm not sure why that would happen, could you give me some additional details?

* Is all of the text missing? Would it be possible to include a screenshot?
* Did you install one of the packages from sourceforge or did you build the code yourself?
* Are you running Debian with a language besides English?

Thanks, Darby

**Comment by cgvirus** [comment]
Hi thanks for your response. Here is the screenshot:
![djv_bug](https://user-images.githubusercontent.com/22106885/47805046-87381a80-dd60-11e8-8b26-5ce39ca88e26.jpg)

-  I installed the deb package form sourceforge.
- No, my Debain is running with English.



- running from terminal says

:
`qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, wayland-egl, wayland, xcb, dxcb, eglfs, linuxfb, minimalegl, vnc, wayland-xcomposite-egl, wayland-xcomposite-glx.

Aborted
`
Running from terminal doesn't start the UI too.

**Comment by cgvirus** [comment]
yes.
ii  libx11-xcb-dev:amd64                                             2:1.6.7-1                               amd64        Xlib/XCB interface library (development headers)
ii  libx11-xcb1:amd64                                                2:1.6.7-1                               amd64        Xlib/XCB interface library
ii  libxcb-composite0:amd64                                          1.13.1-1                                amd64        X C Binding, composite extension
ii  libxcb-damage0:amd64                                             1.13.1-1                                amd64        X C Binding, damage extension
ii  libxcb-dri2-0:amd64                                              1.13.1-1                                amd64        X C Binding, dri2 extension
ii  libxcb-dri2-0-dev:amd64                                          1.13.1-1                                amd64        X C Binding, dri2 extension, development files
ii  libxcb-dri3-0:amd64                                              1.13.1-1                                amd64        X C Binding, dri3 extension
ii  libxcb-dri3-dev:amd64                                            1.13.1-1                                amd64        X C Binding, dri3 extension, development files
ii  libxcb-glx0:amd64                                                1.13.1-1                                amd64        X C Binding, glx extension
ii  libxcb-glx0-dev:amd64                                            1.13.1-1                                amd64        X C Binding, glx extension, development files
ii  libxcb-icccm4:amd64                                              0.4.1-1+b1                              amd64        utility libraries for X C Binding -- icccm
ii  libxcb-image0:amd64                                              0.4.0-1+b2                              amd64        utility libraries for X C Binding -- image
ii  libxcb-keysyms1:amd64                                            0.4.0-1+b2                              amd64        utility libraries for X C Binding -- keysyms
ii  libxcb-present-dev:amd64                                         1.13.1-1                                amd64        X C Binding, present extension, development files
ii  libxcb-present0:amd64                                            1.13.1-1                                amd64        X C Binding, present extension
ii  libxcb-randr0:amd64                                              1.13.1-1                                amd64        X C Binding, randr extension
ii  libxcb-randr0-dev:amd64                                          1.13.1-1                                amd64        X C Binding, randr extension, development files
ii  libxcb-render-util0:amd64                                        0.3.9-1+b1                              amd64        utility libraries for X C Binding -- render-util
ii  libxcb-render0:amd64                                             1.13.1-1                                amd64        X C Binding, render extension
ii  libxcb-render0-dev:amd64                                         1.13.1-1                                amd64        X C Binding, render extension, development files
ii  libxcb-res0:amd64                                                1.13.1-1                                amd64        X C Binding, res extension
ii  libxcb-shape0:amd64                                              1.13.1-1                                amd64        X C Binding, shape extension
ii  libxcb-shape0-dev:amd64                                          1.13.1-1                                amd64        X C Binding, shape extension, development files
ii  libxcb-shm0:amd64                                                1.13.1-1                                amd64        X C Binding, shm extension
ii  libxcb-shm0-dev:amd64                                            1.13.1-1                                amd64        X C Binding, shm extension, development files
ii  libxcb-sync-dev:amd64                                            1.13.1-1                                amd64        X C Binding, sync extension, development files
ii  libxcb-sync1:amd64                                               1.13.1-1                                amd64        X C Binding, sync extension
ii  libxcb-util0:amd64                                               0.3.8-3+b2                              amd64        utility libraries for X C Binding -- atom, aux and event
ii  libxcb-xf86dri0:amd64                                            1.13.1-1                                amd64        X C Binding, xf86dri extension
ii  libxcb-xfixes0:amd64                                             1.13.1-1                                amd64        X C Binding, xfixes extension
ii  libxcb-xfixes0-dev:amd64                                         1.13.1-1                                amd64        X C Binding, xfixes extension, development files
ii  libxcb-xinerama0:amd64                                           1.13.1-1                                amd64        X C Binding, xinerama extension
ii  libxcb-xinput0:amd64                                             1.13.1-1                                amd64        X C Binding, xinput extension
ii  libxcb-xkb1:amd64                                                1.13.1-1                                amd64        X C Binding, XKEYBOARD extension
ii  libxcb-xv0:amd64                                                 1.13.1-1                                amd64        X C Binding, xv extension
ii  libxcb1:amd64                                                    1.13.1-1                                amd64        X C Binding
ii  libxcb1-dev:amd64                                                1.13.1-1                                amd64        X C Binding, development files
ii  qt5dxcb-plugin:amd64                                             1.1.11-2                                amd64        Qt platform theme integration plugin for DDE

**Comment by darbyjohnston** [comment]
Thanks, I'll download Debian and try to reproduce the issue.

**Comment by darbyjohnston** [comment]
Hi,

I was able to install Debian Buster/Sid on a VM and I am also seeing the missing text, although I'm getting a different error message:
QFontDatabase: Cannot find font directory

I have a fix for that but I think it's unrelated to the the "xcb" error. Out of curiosity which desktop are you running on? I just accepted the default Debian desktop during the installation.

**Comment by cgvirus** [comment]
Hi, I am using GNOME 3.30.1

**Comment by darbyjohnston** [comment]
I just uploaded a new version which should fix the font issue, please give it a try and let me know how it goes; it's available here:
http://djv.sourceforge.net/Download.html

**Comment by cgvirus** [comment]
THANKS a LOT for your hard work! It's working properly. Going to share it on my page right now.

**Comment by darbyjohnston** [comment]
Great news! Definitely send me the link to your page.

**Comment by cgvirus** [comment]
Here it is. I promote OpenSource projects here:
https://www.facebook.com/cgvirus

**Comment by darbyjohnston** [comment]
Thanks!
