### ISSUE TITLE
Image filtering depends on zoom

### ISSUE THREAD

**Issue by zero-radiance** [darbyjohnston/DJV#10]
Hello!

First of all, nice piece of software. :-)

I stumbled across a small issue: image filtering appears to depend on the zoom level.
The viewer seems to alternate between bilinear and point filtering.

Additionally, it would be nice to have a setting which specifies the filtering behavior - typically, you want resampling, but sometimes it's nice to be able to look at "raw" pixels.

Cheers!

**Comment by aberkl** [comment]
Compare to Bug https://github.com/darbyjohnston/DJV/issues/148

**Comment by darbyjohnston** [comment]
Hi, I've added settings so that you can choose which filter you want to use for minification (sp?) and magnification, this will be available in the next version.
