### ISSUE TITLE
Trouble building on OSX

### ISSUE THREAD

**Issue by jminor** [darbyjohnston/DJV#11]
I'm following the build instructions here: http://djv.sourceforge.net/BuildOSX.html
but it fails trying to build OpenEXR. It looks like the `openexr.tar.gz` file is suspiciously small and only contains a few files instead of the whole thing?

```
[ 59%] Performing patch step for 'OpenEXR'
CMake Error: tar: -C: Not found in archive
CMake Error: tar: /Users/joshm/git/djv/djv-git-third-party-Debug/OpenEXR/src/OpenEXR: Not found in archive
CMake Error: Problem extracting tar: /Users/joshm/git/djv/djv-git-third-party/openexr/openexr.tar.gz
make[2]: *** [OpenEXR/src/OpenEXR-stamp/OpenEXR-patch] Error 1
make[1]: *** [CMakeFiles/OpenEXR.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by darbyjohnston** [comment]
Hi Josh,

The openexr.tar.gz archive just contains some patches, I should probably rename it and add a "patch" to the filename so there isn't any confusion. The actual OpenEXR archive is downloaded by CMake during the build process.

It looks like the error is coming from how I'm using the "tar" command in the CMake script; do you mind running these two command and sending me the output:
> which tar
> tar --version

Also which version of OSX and CMake are you running?

Thanks, Darby

**Comment by jminor** [comment]
Versions:
macOS Mojave 10.14.5
`/usr/bin/tar` version `bsdtar 2.8.3 - libarchive 2.8.3`
cmake version 3.15.1 installed via homebrew

With your hint, I was able to get it working. It seems that /usr/bin/tar supports the -C option, but the Makefile is running `cmake -E tar` which uses a version of tar built into cmake. At least in this version of cmake, the built-in tar doesn't support -C. Luckily, in this case the -C was redundant to the cd command earlier on the same line. Simply removing the -C foo/bar option worked for me.

The line in the hand-edited build.make file now reads:
`cd /Users/joshm/git/djv/djv-git-third-party-Debug/OpenEXR/src/OpenEXR && /usr/local/Cellar/cmake/3.15.1/bin/cmake -E tar xf /Users/joshm/git/djv/djv-git-third-party/openexr/openexr.tar.gz`

The rest of the third party modules are happily building... next step will be djv itself :)

**Comment by darbyjohnston** [comment]
Nice, I'll make the change and check it in. Hopefully compiling DJV goes a bit smoother but let me know if you run into anything else.

**Comment by jminor** [comment]
I got it all built & I saw your fix to the -C problem. Thanks!
