### ISSUE TITLE
Export broken in 2.0.3

### ISSUE THREAD

**Issue by tobkum** [darbyjohnston/DJV#12]
The export function in the file menu does nothing in the newest version for me. Same for Annotate, that only opens a small overlay saying "Annotate", but nothing else happens, no matter where I click.
Win 10 latest update, Nvidia RTX 2080Ti with Studio Driver

**Comment by darbyjohnston** [comment]
Hi,

Both the export and annotate functionality are still WIP for the new version, hopefully I can get time for implementing them within the next few weeks.

Darby

**Comment by tobkum** [comment]
Oh, thanks for the clarification! I guess at least Annotate worked in a previous version, so I was wondering. Cheers & keep up the great work!

**Comment by darbyjohnston** [comment]
Hi, I've decided to limit the scope of DJV and not include export functionality with the new version. Sorry for any inconvenience this causes!
