### ISSUE TITLE
AUDIO: Audio fails to work in 2nd cycle (of loop mode)

### ISSUE THREAD

**Issue by darbyjohnston** [darbyjohnston/DJV#124]
Original ticket:
https://sourceforge.net/p/djv/bugs/100/

**Comment by darbyjohnston** [comment]
This should be fixed with the new audio system.

**Comment by aberkl** [comment]
Just a sidenote: I have the impression this problem also occurs in 2.0.3 with clips containing no audio. Awaiting 2.0.4 to see how it works.
