### ISSUE TITLE
Centos7 issues with Beta2

### ISSUE THREAD

**Issue by ddesmond** [darbyjohnston/DJV#13]
Hi!
great work! :)
Have trouble installing the beta2 (rpm -ivh and yum install) give me same errors:
Unkown media type in type 'all/all'
Unkown media type in type 'all/allfiles'

after the installer runs, even if i add LD_LIBRARY_PATH it seems it still cant see djv libavcodec.so.58
which is present in libs subfolder.
What should i do?
(yum doeosnt get any deps whatsoever when installing)
thanks!

**Comment by darbyjohnston** [comment]
Hi,

I think the "unknown media type" messages are OK to ignore; for running DJV, are you using the shell script? Like this:

/usr/local/DJV2/bin/djv.sh

**Comment by ddesmond** [comment]
ok for errors.
yes im using it like so.

**Comment by darbyjohnston** [comment]
Thanks, I just noticed that as well; if you run djv.sh from the install directory it fails, but if you run it with the absolute path it works. I'll fix that for the next version.

And yeah, DJV requires OpenGL so you will need either a gpu card or have a software renderer installed.

**Comment by darbyjohnston** [comment]
OK, I fixed the script so that you can now run it like "/usr/local/DJV2/bin/djv.sh", or "./djv.sh".

**Comment by ddesmond** [comment]
great! will do some more work today! thanks for fast fix! :)

**Comment by ddesmond** [comment]
@darbyjohnston 
https://media.discordapp.net/attachments/312131026367545355/668866334225858613/image0.jpg
here we have new issue with 2.0.5 after removing and installing DJV2 for new version.2.0.5

**Comment by darbyjohnston** [comment]
Hi, this looks similar to another issue which was related to the Nvidia driver:
https://github.com/darbyjohnston/DJV/issues/183

Are you using Nvidia hardware and if so, which driver version? Maybe try upgrading to the latest driver?
