### ISSUE TITLE
Add command line options

### ISSUE THREAD

**Issue by darbyjohnston** [darbyjohnston/DJV#139]
Which command line options should we port from version 1.3, and which new ones should we add? Some new command line options suggested in the forums:

--input_color - Set the input color space
--display - Set the display color space
--view - Set the view color space
(https://sourceforge.net/p/djv/discussion/404107/thread/d144c1ffb6/?limit=25#e29a)

**Comment by filmpipeuser** [comment]
Looking at some of the commands for 1.3, I agree that maybe we don't need most of them anymore. But here's a few I think are needed:

--config - Path to a custom ocio config (which will override the OCIO env if set). This also doesn't require the OCIO to be set, which is often is not (as it has a few problems in other apps).

--fps - Playback framerate for sequences that does not have this in metadata, for example jpg sequences.

**Comment by simonbjork** [comment]
Looking at some of the commands for 1.3, I agree that maybe we don't need most of them anymore. But here's a few I think are needed:

--config - Path to a custom ocio config (which will override the OCIO env if set). This also doesn't require the OCIO to be set, which is often is not (as it has a few problems in other apps).

--fps - Playback framerate for sequences that does not have this in metadata, for example jpg sequences.

**Comment by darbyjohnston** [comment]
A couple more as suggested in https://github.com/darbyjohnston/DJV/issues/171:

--frame_start
--frame_end

**Comment by PiOverFour** [comment]
Also had a look at [RV’s command line options](http://www.tweaksoftware.com/static/documentation/rv/current/html/rv_manual.html#Command_Line_Options). They’re uh… extensive, so probably out of scope here, but a couple of them may be relevant:

-fullscreen | Start in fullscreen mode
-screen int | Start on screen (0, 1, 2, ...)
-pa float | Set the Pixel Aspec Ratio

And of course, `--help`, which should exit after printing command line options.

**Comment by darbyjohnston** [comment]
That's an impressive list of options! The ones you listed seem like good additions.

A couple more off the top of my head:
--version - Print the version and exit
--log_console - Print the log to the console
--init_settings - Initialize settings to their default values

**Comment by PiOverFour** [comment]
I thought of a something that needs attention in the command line: the way to open a sequence is not standard or obvious.
Right now, in order to open an image sequence from the command line, you need to know the exact frame ranges, matching those from `File → Open`, so for instance:
``` sh
djv my_seq.0001-0050,0055.exr
```
It’s also possible to automatically detect file sequences from separate file names with a wildcard, but it doesn’t seem to work (see #230), and anyway it would be good in some scenarios not to let the shell handle the expansion (for instance if for some bad reason you have sequences with different paddings in a given directory).

The command is more commonly written as:
``` sh
djv my_seq.####.exr
```
or:
``` sh
djv my_seq.%04d.exr
```
and the program finds the sequence on its own, replacing the pattern by the frames matching the padding.

**Comment by darbyjohnston** [comment]
That's a good point about the shell expansion, it could also fail if the number of files exceeds the maximum limit. What do you think about just "my_seq.#.exr"? It doesn't handle the case of files with the same name but different padding, but I think that would be very unusual to have in the same directory. Especially since that would run into other problems, like if you tried to render "my_seq.1-1001.exr" and my_seq.0001-1001.exr" to the same directory.

**Comment by PiOverFour** [comment]
I think it would work all right, but the problem I see with it is that users will probably expect to use a number of #s matching the padding. I know that at least Nuke and Natron expect it for input. Blender does too for output, and After Effects almost: it uses [####].
So while not strictly needed, it may be less confusing for users. That being said, if it’s documented (in `--help` for instance) it shouldn’t be a problem.

**Comment by darbyjohnston** [comment]
Good point, I like the simplicity of a single '#' as a wildcard but I agree it would be better to match the other programs usage.

**Comment by darbyjohnston** [comment]
I've added most of the command-line options that were suggested, although I've tweaked the names a bit to make them more consistent with the existing naming conventions. I think the only one I left out was the option for pixel aspect ratio, which doesn't seem that useful to me though I could be wrong. I also added support for using "#" to match sequences, where the number of "#" characters matches the zero padding of the sequence.

This is what the current command-line help looks like:
```
C:\dev\djv1-Debug\build\bin\Debug>djv -h

 djv is an application for the viewing and playback of images and image sequences.

 Usage

   djv [input]... [option, ...]

   Inputs can be files or file sequences. If the auto-detect file sequences setting is enabled, files will automatically be expanded to file sequences. File sequences can be specified with either frame numbers (e.g., render.0001-1000.exr), or '#' wildcards (e.g., render.####.exr).

 Window Options

   -full_screen
   Enable full screen mode.

   -full_screen_monitor (number)
   Set the full screen monitor.

 OCIO Options

   -ocio_config (.ocio file name)
   Set the OCIO configuration.

   -ocio_display (name)
   Set the OCIO display color space.

   -ocio_view (name)
   Set the OCIO view color space.

   -ocio_image (name)
   Set the OCIO image color space.

 Playback Options

   -speed (value)
   Set the playback speed.

   -in_out (value) (value)
   Set the playback in and out points. The values are given in either timecode or frames, based on the time units settings.

   -frame (value)
   Set the current frame. The value is given in either timecode or frames, based on the time units settings.

 UI Options

   -init_settings
   Initialize to factory settings.

 General Options

   -log_console
   Print the log to the console.

   -version
   Print the version and exit.

   -help, --help, -h
   Print this message and exit.

```

**Comment by simonbjork** [comment]
Thanks a lot for adding these!

I just tested with the latest release and something seems broken. When I try with -h, -help, --help nothing prints. Same with -version.

When I try for example -full_screen it works though.

**Comment by darbyjohnston** [comment]
Hi, that's odd, I just tried them and they worked OK for me; out of curiosity what OS are you running on?

**Comment by simonbjork** [comment]
Yes very strange indeed. Windows 10.

**Comment by darbyjohnston** [comment]
Ah, I think I found the issue; are you running "djv.exe"? Try just using "djv" instead. There are actually two DJV executables on Windows, "djv.exe" and "djv.com". When you run "djv" in a command prompt it autoamatically uses the "djv.com" version which has support for the command line flags.

**Comment by simonbjork** [comment]
Thank you, that works as expected. But I must say it's a bit confusing. Expecially as I can still use some of the arguments with djv.exe.

So if I were to create tools that launch djv from another application , I should always use just "djv" and never djv.exe?

**Comment by darbyjohnston** [comment]
It's definitely confusing! I had to look at the code again to remind myself why it works that way. :) I misspoke before, both "djv.exe" and "djv.com" should accept the same arguments, the main difference is that "djv.com" can print to the command prompt, while "djv.exe" cannot. That's why it looks like "djv.exe" doesn't work with the "-h/-help" options, it just doesn't have the capability to print out the help.

If you are launching DJV from another application it should be OK to use "djv.exe" with arguments, but if you want to see the help/version on the command line you need to use "djv" or "djv.com".

**Comment by simonbjork** [comment]
Ok thanks for clearing that up :). I'll do some tests!
