### ISSUE TITLE
DJV 2.0.3 very slow to launch on Windows

### ISSUE THREAD

**Issue by DabuXian** [darbyjohnston/DJV#144]
Not sure if it's a known issue, but 2.0.3 has been extremely slow to launch on Windows 10, it takes about 20-30 seconds every time. In comparison 1.30 is almost instantaneous.

I've tested it on 3 different computers, the best one has pretty good specs (i7 8700k, Geforce 1080 Ti, 32 GB RAM, SSD storage), so I'd assume it's a problem with DJV, not the hardware. Also tested on two different builds of Windows 10 (1903 and 1809) and it's the same on both.

**Comment by darbyjohnston** [comment]
Hi,

I'm sorry to hear that, on my Windows 10 machines the launch time is very similar, so I'm not sure why it is slow on your systems. Would you mind sending me the log file so I can troubleshoot it? It is located in your "Documents" directory, like:

C:\Users\darby\Documents\DJV\djv.log

Thanks, Darby

**Comment by DabuXian** [comment]
Interesting. So I guess it's a problem on our end, not sure what could possibly cause it though. Anyway, here's the log.

[djv.log](https://github.com/darbyjohnston/DJV/files/3620751/djv.log)

**Comment by darbyjohnston** [comment]
Hi,
Thanks for the log; I can see where it pauses during startup for about 30 seconds, though I am not sure why. Is the installation and account you are running from local to the machine (not over the network)?


Darby

    On Tuesday, September 17, 2019, 3:39:48 AM PDT, DabuXian <notifications@github.com> wrote:  
 
 
Interesting. So I guess it's a problem on our end, not sure what could possibly cause it though. Anyway, here's the log.

djv.log

**Comment by DabuXian** [comment]
Yeah, it's local.

I figured it out actually, seems like our antivirus (Eset Nod32) is causing this. Adding DJV2 folder to its exceptions fixes it. That's the beauty of using obscure antivirus software I guess. :D Sorry for bothering you, should've guessed it. Thanks for trying to help.

**Comment by darbyjohnston** [comment]
No worries, I'm glad you were able to sort it out. I've put a fair bit of work into making the startup time fast for the new version so I'm glad it wasn't my fault. :)

**Comment by SebABF** [comment]
I'm unable to get DJV to open on my PC... This is at the bottom of the log: 
01/18/22 10:48:40            djv::AV::GLFW::System | OpenGL version: 4.1.0
01/18/22 10:48:40            djv::AV::OCIO::System | djv::AV::OCIO::System starting...
01/18/22 10:48:40            djv::AV::OCIO::System | OCIO version: 1.1.1
01/18/22 10:48:40                djv::AV::AVSystem | djv::AV::AVSystem exiting...
01/18/22 10:48:40            djv::AV::GLFW::System | djv::AV::GLFW::System exiting...
01/18/22 10:48:40            djv::AV::OCIO::System | djv::AV::OCIO::System exiting...
01/18/22 10:48:40            djv::Core::CoreSystem | djv::Core::CoreSystem exiting...
01/18/22 10:48:40     djv::Core::Animation::System | djv::Core::Animation::System exiting...
