### ISSUE TITLE
Fix FFmpeg installation on Windows

### ISSUE THREAD

**Issue by darbyjohnston** [darbyjohnston/DJV#159]

**Comment by Fragrag** [comment]
Hi,

I am unable to build the solution on Windows, starting from commit 69ac0c0. The previous commit b8fdb70 still builds properly, albeit without ffmpeg.

I get the error `LNK1104 cannot open file 'FFmpeg::avformat-NOTFOUND.obj' from the following projects: 
![image](https://user-images.githubusercontent.com/11410248/69185744-8e6ec980-0b17-11ea-90fe-208057e6dc37.png)

**Comment by darbyjohnston** [comment]
Hi,

Sorry about that, I need to come up with a better fix for my "fix"; in the meantime you can fix the build locally by commenting out the "FFmpeg" on line 191 in the root CMakeLists.txt file.
