### ISSUE TITLE
Switching Layer in OpenEXR disables cache

### ISSUE THREAD

**Issue by tiltX** [darbyjohnston/DJV#162]
When switching layers using the Layer dialog (ctrl-L) in 2.0.5 the cache seems to get disabled. The colored caching bars are gone at first. When clicking the cache icon, the checkbox is still enabled, and clicking it twice (to disable and re-enable it) the orange and green bars re-appear and DJV fills the cache once again.

**Comment by darbyjohnston** [comment]
Thanks for the bug report, I'll check it out.

**Comment by darbyjohnston** [comment]
Hi, I just checked in a fix for this and it will be included with the next release.
