### ISSUE TITLE
ERROR: Error loading image: ...\64DPI\djvIconPlaybackReverse.png

### ISSUE THREAD

**Issue by LichiMan** [darbyjohnston/DJV#163]
Hi,

I'm just testing the new 2.0.5 release on Windows and I get this error:
ERROR: Error loading image 'C:\Users\blue\Downloads\DJV-2.0.5-win64\etc\Icons\64DPI\djvIconPlaybackReverse.png'.

I downloaded the .zip version.

Nice release btw! :)
Thanks.

**Comment by LichiMan** [comment]
Also I get the next error when I run it for the first time or I delete the preferences:
ERROR: Error loading image 'C:\Users\blue\Downloads\DJV-2.0.5-win64\etc\Icons\64DPI\djvLogoStartScreen.png'.

**Comment by darbyjohnston** [comment]
Hi,

Thanks for the bug report, I'll check it out. Out of curiosity what resolution is your monitor?

Darby

**Comment by LichiMan** [comment]
Hi Darby,

I have two monitors with a resolution of 1920x1200 each.

Thanks.

**Comment by darbyjohnston** [comment]
This should be fixed now, there were some resolutions of djvIconPlaybackReverse.png that were missing, and also a couple of issues with the icon system. These fixes will be included with the next release.
