### ISSUE TITLE
BUG: DJV 2.0.5 - shortcut FRAMESTORE "F" does not work

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#164]
DO:
	- load any clip
	- navigate to a "special position"
	- SHIFT + F to load into frame store
	- navigate to "another position"
	- press F to show content of frame store

	HAPPEN
	- still shows "another position"

	SHOULD:
	- show content of frame store on "special position"

	NOTES:
	- toggling IMAGE > FRAME STORE works as expected
	- a very valuable feature, please make it work

**Comment by darbyjohnston** [comment]
Ah yes, sorry about that, looks like I accidentally assigned the "F" shortcut to another action. I'll fix this for the next version.

**Comment by darbyjohnston** [comment]
I accidentally assigned the "F" shortcut to the action for "fitting" the window to the image; I've changed that to "Ctrl+F" so the frame store shortcut works again now.
