### ISSUE TITLE
Localization review: Spanish

### ISSUE THREAD

**Issue by jonbragado** [darbyjohnston/DJV#166]
Hi Darby, 

I have downloaded the latest version of djv 2.0.5 and found the locale folder for all the strings in Spanish.
Couple of questions here as I am not a programmer myself. I use QtLinguist and POEdit to do the translations, but somehow, the formatting of the .txt file fails to convert to any of these formats so the translation can begin in a more systematic way, for example, building a glossary so the translation is always consistent. 
I can hard code the translation but any new version of the software that has a new feature will require a rerun to find what the new strings are and sometimes it means restarting again. 

The second thing is the encoding. A string like this one: "No tiene ninguna *transmisi\u00f3n* de video o audio."
The *\u00f3* part makes the translation process and correction more complicated, as the most efficient way for me would be to write *transmisión* instead of *transmisi\u00f3n*, otherwise every word that it would have the tilde in a different position it would be very hard to track down. 

So far the machine translate attempt has a very good base, I think it needs a bit of a tidy job to make it be excellent. :)

Thanks,

**Comment by darbyjohnston** [comment]
Hi,

Thanks for the feedback, the current system definitely leaves a lot to be desired. I'll check out POEdit/gettext and see if that's something I can integrate.

You are also the first person to compliment the machine translations. :)

Darby

**Comment by darbyjohnston** [comment]
Spanish translations have been updated with:
https://github.com/darbyjohnston/DJV/issues/182
