### ISSUE TITLE
DJV Requests Ignored 

### ISSUE THREAD

**Issue by SheepDomination** [darbyjohnston/DJV#167]
I made numerous requests for version 2.x of DJV view but it appears they were all ignored.

**Comment by Fragrag** [comment]
Hi, what were you exactly requesting and where?

**Comment by SheepDomination** [comment]
I wrote it under _Issues_.

**Comment by darbyjohnston** [comment]
Hi, it certainly wasn't intentional; a lot of work went into the new version and there is still a lot more to do. Can you link to the requests you made? Was it on GitHub or SourceForge?

Darby

**Comment by SheepDomination** [comment]
It was on SouceForge.

**Comment by SheepDomination** [comment]
What is the link to the DJV on Source Forge ?

**Comment by darbyjohnston** [comment]
https://sourceforge.net/p/djv/_list/tickets

**Comment by darbyjohnston** [comment]
I also made copies on GitHub of all the open issues on SourceForge so they may also be here:
https://github.com/darbyjohnston/DJV/issues

**Comment by SheepDomination** [comment]
[Here](https://sourceforge.net/p/djv/discussion/404107/thread/f8ae3ffdeb/?limit=25#f5e9), these are the issues I was hoping would be resolved in 2.x.

**Comment by SheepDomination** [comment]
Also the old scrubber from version 1.0; I'd like to see brought back, it was more effective then current version.

**Comment by darbyjohnston** [comment]
Could you be more specific? I just compared scrubbing between version 1.3 (ctrl+left mouse) and 2.0.5 (right mouse) on a 700 frame sequence and it felt similar. Or do you mean the buttons for scrubbing that were on the timeline in 1.3?

> How do I write an annotation; I can create the Annotation window, but I can't write anything ?

Annotations are still a work in progress for 2.0, they will hopefully be added in the next version.

> There is no option of loading a custom LUT in DJV ? 

DJV supports loading LUTs through OpenColorIO; I have not tried adding a custom LUT to OCIO, there might be information about that here:
https://opencolorio.org/

Once you have created a custom OCIO configuration this is how you can add it to DJV:
https://darbyjohnston.github.io/DJV/djv_color.html

> Also the split window issue I mentioned here;

Window snapping would be useful, I'll add a GitHub issue for it but cannot promise when it will be implemented:
https://github.com/darbyjohnston/DJV/issues/168

> Plugging into DCC applications, yes; I mean, Maya, Houdini, Blender, Max

I've created issues for each of these, the only one I have access to currently is Blender so again I can't promise when they will be implemented:
https://github.com/darbyjohnston/DJV/issues/30
https://github.com/darbyjohnston/DJV/issues/169
https://github.com/darbyjohnston/DJV/issues/170
https://github.com/darbyjohnston/DJV/issues/171

**Comment by SheepDomination** [comment]
> Or do you mean the buttons for scrubbing that were on the timeline in 1.3?

The buttons which were on the timeline in 1.3; I would like to see them brought back.

>Annotations are still a work in progress for 2.0, they will hopefully be added in the next version.

I look forward to this. As well as Issue #168.

**Comment by darbyjohnston** [comment]
I created an issue for adding scrubbing buttons to the timeline:
https://github.com/darbyjohnston/DJV/issues/175

I'm going to close this issue since it is overly broad and all the specific feature requests now have issues associated with them.
