### ISSUE TITLE
DJV cannot start from CLI on Windows if not executed from bin directory.

### ISSUE THREAD

**Issue by KelSolaar** [darbyjohnston/DJV#172]
We are using Rez and our fresh DJV package adds `DJV/bin` to `%PATH%`. Unfortunately, then when trying to launch DJV, it does not start from CLI if the CWD is not `DJV/bin` :

```
ERROR: The program 'etc\Shaders\djvAVRender2DVertex.glsl' cannot be linked. Vertex info
-----------
(0) : error C5145: must write to gl_Position
```

This can be solved by using a `.bat` file as follows:

```cmd
set CWD=%cd%
cd /d %~dp0
djv.exe
cd /d %CWD%
exit
```

but this imposes to run `djv.bat` instead of `djv` which is annoying.

Cheers,

Thomas

**Comment by darbyjohnston** [comment]
Hi,

Thanks for reporting this, I'll check it out. Another workaround is to set the "DJV_RESOURCE_PATH" to the location of the installation directory (e.g., "C:\Program Files\DJV2").
https://darbyjohnston.github.io/DJV/env_vars.html

Darby

**Comment by KelSolaar** [comment]
Thanks @darbyjohnston, that worked well!

**Comment by darbyjohnston** [comment]
Hi, I checked in a fix for this and will include it with the next release. DJV was trying to use the command-line arguments to find the installation path, now it will also check the search path.

**Comment by KelSolaar** [comment]
Awesome thanks Darby!
