### ISSUE TITLE
Support for CPack to automate package creation

### ISSUE THREAD

**Issue by jfpanisset** [darbyjohnston/DJV#176]
Consider using CPack from CMake to automate package creation as part of the CI build process. CPack should support all the required package formats, including dmg and MSI.

https://cmake.org/cmake/help/latest/manual/cpack-generators.7.html

**Comment by darbyjohnston** [comment]
Hi, DJV does currently use CPack for package creation, including dmg and MSI files. A nice thing to add would be to have the CI process generate those packages and deploy them automatically as GitHub releases; I have a separate issue for that, so if you don't mind I'm going to close this issue.
https://github.com/darbyjohnston/DJV/issues/156
