### ISSUE TITLE
Support for CTest to drive test suite

### ISSUE THREAD

**Issue by jfpanisset** [darbyjohnston/DJV#177]
Consider leveraging CTest to drive the test suite, and possible upload test results to the CDash console. Some experimentation with uploading to CDash:

https://github.com/jfpanisset/aswf-sample-project#uploading-ctest-results-to-cdash

**Comment by jfpanisset** [comment]
Nevermind, looks like CTest is already being used.

**Comment by darbyjohnston** [comment]
As I mentioned in the other issue (https://github.com/darbyjohnston/DJV/issues/155#issuecomment-559893676), DJV does use CTest for running the test suite but it would be nice to get CDash support enabled.
