### ISSUE TITLE
Spanish translation update

### ISSUE THREAD

**Issue by CansecoGPC** [darbyjohnston/DJV#182]
Hi,

I recently tried DJV 2.0.5 on Linux, but i found some spanish translations were a bit weird, but not bad for an AI.
Everything should be correct now, but maybe i missed something, i'm only human after all, XD

[dvj-es.zip](https://github.com/darbyjohnston/DJV/files/3935355/dvj-es.zip)

**Comment by darbyjohnston** [comment]
Hi, sorry for the delay, and thanks for the contribution! This will be the first test to see how updating the machine translations works, I'll add it for the next release. I was going to add a section in the credits for people who help out with the translations, would you like to be listed?

Thanks, Darby

**Comment by CansecoGPC** [comment]
No problem, i was busy fixing Blender internal add-ons, to each their own, XD
About being listed in the credits, sure, just copy paste my nickname.

Thanks for this great piece of software, makes my life more easier.

**Comment by darbyjohnston** [comment]
I've checked this in for the next release, thanks again!
