### ISSUE TITLE
Failed to build on CentOS 7.7

### ISSUE THREAD

**Issue by zhiyiliparker** [darbyjohnston/DJV#183]
Hi,

I failed to build the DJV, it looks like it's stopped because of the libGLX.so
" No rule to make target '/usr/lib64/libGLX.so' " .

Below is the detail errors.

```
Scanning dependencies of target Render2DStressTest
[ 75%] Building CXX object lib/djvUI/CMakeFiles/djvUI.dir/Tooltip.cpp.o
[ 75%] Building CXX object lib/djvUI/CMakeFiles/djvUI.dir/UISettings.cpp.o
make[2]: *** No rule to make target '/usr/lib64/libGLX.so', needed by 'build/bin/Render2DStressTest'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 75%] Building CXX object tests/Render2DStressTest/CMakeFiles/Render2DStressTest.dir/Render2DStressTest.cpp.o
Scanning dependencies of target djv_convert
make[2]: *** No rule to make target '/usr/lib64/libGLX.so', needed by 'build/bin/djv_convert'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 76%] Building CXX object bin/djv_convert/CMakeFiles/djv_convert.dir/main.cpp.o
[ 76%] Building CXX object lib/djvUI/CMakeFiles/djvUI.dir/UISystem.cpp.o
[ 76%] Building CXX object lib/djvUI/CMakeFiles/djvUI.dir/Widget.cpp.o
[ 76%] Building CXX object lib/djvUI/CMakeFiles/djvUI.dir/Window.cpp.o
Scanning dependencies of target djv_info
make[2]: *** No rule to make target '/usr/lib64/libGLX.so', needed by 'build/bin/djv_info'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 76%] Building CXX object bin/djv_info/CMakeFiles/djv_info.dir/main.cpp.o
Scanning dependencies of target djv_ls
make[2]: *** No rule to make target '/usr/lib64/libGLX.so', needed by 'build/bin/djv_ls'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 76%] Building CXX object bin/djv_ls/CMakeFiles/djv_ls.dir/main.cpp.o
make[1]: *** [CMakeFiles/Makefile2:1538: bin/djv_info/CMakeFiles/djv_info.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1600: bin/djv_ls/CMakeFiles/djv_ls.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1387: tests/Render2DStressTest/CMakeFiles/Render2DStressTest.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1476: bin/djv_convert/CMakeFiles/djv_convert.dir/all] Error 2
[ 77%] Linking CXX static library ../../build/lib/libdjvUI.a
[ 77%] Built target djvUI
make: *** [Makefile:163: all] Error 2
```

the OpenGL and my nvidia display driver on my machine should be installed correctly, since I tried to execute the command  glxinfo | grep "OpenGL"  in terminal and got the following results:

```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1060/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 430.50
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 430.50
OpenGL shading language version string: 4.60 NVIDIA
```

Also, the libGLX.so has been stored in /usr/lib64/ and /usr/lib/ directories on my machine.

Any thoughts? 
Thanks in advance for your help.

**Comment by darbyjohnston** [comment]
Hi,

I'm not sure what is causing that, I have a similar setup and the build is working OK here. Could you attach the full output from the CMake command?

Darby

**Comment by zhiyiliparker** [comment]
Problem solved and here's what I've found after multiple failed experiments. 

First of all, the issue I posted above was caused by the following broken symbolic links
```
    /usr/lib64/libGLdispatch.so 
    /usr/lib64/libGL.so 
```
I fixed the issue through the following commands, which I re-linked them to a correct  .so file
```
    sudo ln -sf /usr/lib64/libGLdispatch.so.0 /usr/lib64/libGLdispatch.so
    sudo ln -sf /usr/lib64/libGL.so.1.7.0 /usr/lib64/libGL.so
```

Then I encountered another issue, where the error message told me that:
`    /usr/lib64/libOpenGL.so undefined reference to `_glapi_tls_Current' `

According to [Nvidia forum](https://devtalk.nvidia.com/default/topic/1050786/linux/nvidia-drivers-430-09-causes-xorg-segfault-at-start-/3), Nvidia has introduced some changes for the driver since version 430.XX,  so the compilation of DJV becomes a bit tricky, currently I'm using version 430.50 and my workaround for this issue is to re-link the symbolic link file:
    
`    sudo ln -sf /usr/lib64/libGL.so.1.7.0 /usr/lib64/libOpenGL.so`

Now I can build DJV successfully after above workarounds, hope they could help people who encounters the similar issues. 

Cheers,
Parker

**Comment by darbyjohnston** [comment]
Hi, sorry for the troubles but I'm glad you got it resolved and posted the solution. I guess I haven't run into that on my CentOS box since I haven't updated in awhile.

Thanks, Darby
