### ISSUE TITLE
Hangs on right click

### ISSUE THREAD

**Issue by gez** [darbyjohnston/DJV#187]
DJV 2.0.5 for Windows.
Consistently hangs every time I right click on the image. The program has to be killed and relaunched to keep working.

**Comment by darbyjohnston** [comment]
Hi, thanks for the bug report; it looks like this only happens for single images, with sequences/movies the right mouse button scrubs the current frame without hanging. I'll get this fixed for the next release.

**Comment by darbyjohnston** [comment]
OK, I just checked in a fix for this, it will be included in the next release.
