### ISSUE TITLE
simple video sequence mode

### ISSUE THREAD

**Issue by alfsici** [darbyjohnston/DJV#188]
Love the new Djv, i am not sure this is something you already thought of , but a feature im currently lacking is to be able to play more then 1 video in sequence in the same viewer.
This is very handy while working on animation, to evaluate a few shots while playing out before and after the one you are currently working on and to look at how it flows in the sequence.

Ideally it should be a very simple view mode, where each single video can be trimmed to an in and out frame (as it currently is) ,moved up or down (before or after ) and in a layered fashion the sequence would play a video after the other keeping in account the cut range, this could be the "sequence" viewer.
Once a playblast/movie gets updated, it can override the one currently in the viewer, and DjV would notice the update or a simple manual refresh command can be run,refreshing the video,and keeping the workflow very efficient.

**Comment by darbyjohnston** [comment]
Hi, thanks for the suggestion, sequences/playlists are definitely something I would like to add support for. There's actually an existing issue for this, so I'm going to close this one as a duplicate, but please feel free to add any ideas/feature requests in the other issue:
https://github.com/darbyjohnston/DJV/issues/16

Out of curiosity how do you deal with the editorial information? Are you using an EDL or some other editorial format?
