### ISSUE TITLE
[X-WINDOWS] DJV fails to launch after launching

### ISSUE THREAD

**Issue by sobotka** [darbyjohnston/DJV#192]
**Summary**: After having successfully launched DJV, DJV fails to launch on X-Windows. Pulling in new master and resultant build also fails to launch.

**Build**: cba4b36c9ce9889ca3936fd177a1efb23c164049

**CLI Output**:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0x0
  Serial number of failed request:  225
  Current serial number in output stream:  225
```

**Platform**: `Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux`

**Comment by darbyjohnston** [comment]
Hi, could you try deleting the DJV settings file and see if it starts OK after that? The file is located here: "$HOME/Documents/DJV/djv.json"

Thanks, Darby

**Comment by sobotka** [comment]
Confirming that it starts fine after that.

**Comment by darbyjohnston** [comment]
Great, thanks; I wonder if it is saving a bad window size in the settings. Would you mind diffing the settings files? Something like:

```
rm $HOME/Documents/DJV/djv.json
djv
cp $HOME/Documents/DJV/djv.json $HOME/Documents/DJV/djv.json.TEMP
djv
diff $HOME/Documents/DJV/djv.json $HOME/Documents/DJV/djv.json.TEMP

**Comment by darbyjohnston** [comment]
Closing this since I never heard back and cannot repro...
