### ISSUE TITLE
DJV 2.0.5 - MENU > VIEW moves wrong direction when using KEY PAD shortcuts

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#194]
DO:
- open any image
- press KEY PAD 8

HAPPEN
- image moves DOWN

SHOULD:
- move UP

NOTES:
- MENU > VIEW > UP actually says KEY PAD 8 for UP, but does what KEY PAD 2 is meant to do

**Comment by darbyjohnston** [comment]
In this case the "view" is moving, not the image, which is why it feels reversed. I can see how both could be useful though, how about a setting for switching between the two modes?

**Comment by aberkl** [comment]
Okay, I get your point. Still feels very odd when pressing upper left "7" and see the image move to lower right. For me (whoami?) this seems counter-intuitive.

**Comment by darbyjohnston** [comment]
I think it is a personal preference; for example when the image is zoomed in, moving the "view" seems much more intuitive for me. I'll add a setting for toggling the behavior.

**Comment by aberkl** [comment]
> I think it is a personal preference; for example when the image is zoomed in, moving the "view" seems much more intuitive for me. 

Maybe not that important at all, I personally always loved the "pan view" using mouse mid-button & "drag canvas" behaviour (which is still available).

**Comment by darbyjohnston** [comment]
Thanks, that's my favorite as well, especially with the "+" and "-" keyboard shortcuts for zooming into where the mouse cursor is. I don't use the arrow keys that often but they can be a nice alternative when using the mouse gets tiring.

**Comment by aberkl** [comment]
> Thanks, that's my favorite as well, especially with the "+" and "-" keyboard shortcuts for zooming into where the mouse cursor is. I don't use the arrow keys that often but they can be a nice alternative when using the mouse gets tiring.

My all-time-favorite is turn mouse wheel at "Mouse wheel zoom factor 100%"... 
So basically WHEEL PRESS to move, WHEEL TURN to zoom in/out. Never experienced anything as fast as this in any software other than DJV 1.x ;-)

**Comment by darbyjohnston** [comment]
Sorry about that, the mouse wheel scrolling is broken in the current version, I made a new issue to address that:
https://github.com/darbyjohnston/DJV/issues/199

(I mostly use a tablet so hadn't noticed...)

**Comment by darbyjohnston** [comment]
On second thought I've reversed the direction of the key pad shortcuts, so that pressing "Up" on the key pad moves the image up, etc. This also matches what the mouse drag does. It feels fine to me (though sometimes I like the opposite behavior), and I'm wary of adding more settings. :)
