### ISSUE TITLE
Issue with vertical orientation in some EXR files

### ISSUE THREAD

**Issue by jfpanisset** [darbyjohnston/DJV#195]
The following thread on the openexr-dev mailing list seems to imply that DJV may not be handling the vertical orientation of OpenEXR files correctly, and some images will appear flipped vertically compared to Nuke or exrdisplay.

https://lists.aswf.io/g/openexr-dev/topic/openexr_rgbaoutputfile_is/70222932?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,70222932

**Comment by darbyjohnston** [comment]
Thanks for creating the issue, I'll add this for the next release.

**Comment by charlie-volpe** [comment]
Thanks for the help with figuring this out in the openexr-dev mailing list. :)

**Comment by darbyjohnston** [comment]
Hi, this was broken with the older version of DJV (1.3), but is fixed in the new 2.0 versions. I've verified this with the example image from the linked thread.
