### ISSUE TITLE
DJV 2.0.5 - odd green "something" in menu bar once a file is opened

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#196]
DO:
- open any image/sequence or clip 

HAPPEN
- in menu bar a green "something" appears:

![ksnip_20200129-230612](https://user-images.githubusercontent.com/9915206/73401992-9489df00-42ec-11ea-92b3-f6fe3a5d2280.png)

Should:
- not

**Comment by aberkl** [comment]
I see, the green "something" is an indicator bar for the memory cache, the higher the bar the more memory is used. I guess that is okay, only when little memory is used it looks like a UI design glitch.

**Comment by darbyjohnston** [comment]
I was trying to make something like a small "thermometer" to show the memory cache usage, something that would take up less space than a text label. There is a tooltip for it so if you hover the mouse over it to discover what it is. Also if you want to see the percentage number you can click on the memory cache settings button next to it.

**Comment by aberkl** [comment]
> There is a tooltip for it so if you hover the mouse over it to discover what it is. Also if you want to see the percentage number you can click on the memory cache settings button next to it.

Can you show the percentage in the tooltip like "**Memory cache usage: 12%**"?
