### ISSUE TITLE
Show RGB layer channel support

### ISSUE THREAD

**Issue by dynestudio** [darbyjohnston/DJV#197]
Hi! It is possible to show the RGB channels at the same time of each layer? I noticed that right now I can see each channel from each layer with the layer manager:

[img01](https://i.imgur.com/VgGnID8.png)

But also it can be useful visualize the 3 channels at the same time, like in comp softwares:

[img02](https://i.imgur.com/Z2PEWTv.jpg)

Or like in the old version:

[link ](https://github.com/darbyjohnston/DJV/issues/4)

If there is an option to do this please don't pay attention to this request.

Thanks!

**Comment by darbyjohnston** [comment]
Hi, the individual layers should be grouped together automatically but right now it only works if the names are like "layer.r", "layer.g", "layer.b". It would be nice to make this configurable but for now I can also add the logic for recognizing names like "layer.red", "layer.green", and "layer.blue".

**Comment by dynestudio** [comment]
That should work fine also, thanks :).

**Comment by darbyjohnston** [comment]
Great! Sorry I forgot to ask, could you possibly send me one of your images so I can verify that my fix works? If you don't want to post it publicly on GitHub you can also email it to me directly (darbyjohnston@yahoo.com).

**Comment by dynestudio** [comment]
Sure no problem, I already sent to your mail, let me know if you need something more and thanks so much for this feature, cheers!

**Comment by darbyjohnston** [comment]
Thanks! I just checked in a fix for this and it will be included with the next release.

**Comment by dynestudio** [comment]
Awesome, thanks!
