### ISSUE TITLE
Incorrect color display in Mov Files

### ISSUE THREAD

**Issue by dynestudio** [darbyjohnston/DJV#198]
Hello!

Seems like the color display in mov files looks a little bit different compared to a image sequence:

[Example 01](https://i.imgur.com/R808y11.jpg)
[Example 02](https://i.imgur.com/F3lNMlb.jpg)

The correct color are from the image sequence. Also seems like the color space UI doesn't work with mov files right?

[Example](https://i.imgur.com/G1cipBb.gifv)

**Comment by darbyjohnston** [comment]
Hi, thanks for reporting this, it looks like movie files are not getting the color spaces applied. I'll add this as a bug to get fixed for the next release.

**Comment by dynestudio** [comment]
Great, glad to hear it, thanks!

**Comment by darbyjohnston** [comment]
Hi, this should be fixed now and will be included in the next release. Note that by default the movie files will use the sRGB color space, to override that:

1. Add a color space override for "FFmpeg"
2. Set the color you would like to use

![DJV Color Space](https://user-images.githubusercontent.com/8532558/73567385-27c13280-441b-11ea-9cf2-4133f7c96df0.png)

**Comment by dynestudio** [comment]
Thanks!
