### ISSUE TITLE
DJV 1.2.2 & 1.2.3 image rotation issues

### ISSUE THREAD

**Issue by craGato** [darbyjohnston/DJV#2]
Wrong rotation. Rotation worked as expected on v1.1.0

No rotation v1.2.3
![imagen](https://user-images.githubusercontent.com/36661754/48068353-e2d82d00-e1d2-11e8-9ce1-37c145207cc4.png)

Rotated 90º v1.1.0
![imagen](https://user-images.githubusercontent.com/36661754/48068576-74479f00-e1d3-11e8-8372-17273143e9b7.png)

Rotated 90º v1.2.3
![imagen](https://user-images.githubusercontent.com/36661754/48068368-eec3ef00-e1d2-11e8-8bc5-1c9daf074d9b.png)

Rotated 180º v1.2.3
![imagen](https://user-images.githubusercontent.com/36661754/48068503-4b270e80-e1d3-11e8-9e30-6c2eb3183955.png)

Rotated 270º v1.2.3
![imagen](https://user-images.githubusercontent.com/36661754/48068477-364a7b00-e1d3-11e8-892a-51995adf8793.png)

**Comment by darbyjohnston** [comment]
Sorry about that! I have a fix and will release it later today or tomorrow. Also thanks for the screenshots.

**Comment by darbyjohnston** [comment]
I just released a new version that fixes this issue, you can download it here:
http://djv.sourceforge.net/Download.html
