### ISSUE TITLE
DJV 2.0.5 - AUDIO icon identical for MUTE and NO AUDIO

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#204]
DO:
- open a clip with audio
- MUTE audio
- open a clip without audio

HAPPEN:
- both show SPEAKER "Xed"

![AudioIcon](https://user-images.githubusercontent.com/9915206/73724455-b25fa580-472b-11ea-8ae4-98f529c9c878.png)
SHOULD:
- be clear if MUTEed or NO AUDIO

**Comment by darbyjohnston** [comment]
Instead of changing the icon I've hidden the button when a clip doesn't have any audio. That way it's clear which clips have audio, and clips without audio gain a bit of extra space for the timeline.
