### ISSUE TITLE
DJV 2.0.5 - issues with localisation

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#205]
**Some keyboard shortcut translations contain a dot ".":**
```
grep '"[A-Z]\."' *.text
djvUI.de.text:        "text": "O.", 
djvUI.de.text:        "text": "Q.", 
djvUI.de.text:        "text": "Y.", 
```
**Additionally some keyboard shortcut translations result in strange translations:**
```
    {
        "source": "I", 
        "text": "ich", 
        "id": "I", 
        "description": ""
    }, 
```
**This results in funny things like:**
![ksnip_20200204-093311](https://user-images.githubusercontent.com/9915206/73727154-3a947980-4731-11ea-8b36-c41175af455b.png)
Not sure if this is possible, but a single character shortcut (like "1" or "O") should never be translated (by the machine...

**Comment by darbyjohnston** [comment]
I've removed the translations for the single characters so these should appear OK now, this will be included with the next release. I'm not sure how the keyboard shortcuts work with non-English keyboards, but maybe that is part of the work for the custom keyboard shortcuts:
https://github.com/darbyjohnston/DJV/issues/72
