### ISSUE TITLE
DJV 2.0.5 - PIP has original image orientation

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#206]
DO:
- load a clip with upside down/180° rotated image content
- mirror H + V to see it properly
- hover timeline

HAPPEN:
- original orientation

![ksnip_20200204-094628](https://user-images.githubusercontent.com/9915206/73728112-0621bd00-4733-11ea-9d7d-16c17513d1ee.png)

SHOULD:
- use image transform (here mirror H + V) for PIP

**Comment by darbyjohnston** [comment]
This is fixed and will be included with the next release. I also fixed the PIP to properly display the image rotation.
