### ISSUE TITLE
DJV 2.0.5 - tooltips appear when hovering window title bar above item

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#207]
DO:
- hover window title bar i.e. above MEMORY icon

HAPPEN:

![ksnip_20200204-145708](https://user-images.githubusercontent.com/9915206/73750994-78f45d80-475e-11ea-9613-29a82003c654.png)

SHOULD:
- not show tooltip when not hovering a "tooltipped" item

**Comment by darbyjohnston** [comment]
Good call, that one has been annoying me as well.

**Comment by darbyjohnston** [comment]
This should be fixed now and will be included with the next release.
