### ISSUE TITLE
DJV 2.0.5 - "Rotate" dropdown should show i.e. "180°"

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#208]
DO:
- MENU > IMAGE > IMAGE CONTROLS > TRANSFORM

HAPPEN:
- ROTATE shows i.e. "180"

![RotateShouldHaveDegrees](https://user-images.githubusercontent.com/9915206/73869761-32306180-484b-11ea-94d5-668ffd77522b.png)

SHOULD:
- ROTATE shows "180^"

NOTES:
- I tried using the locales just to find "0" (zero) is used elsewhere as a plain zero

**Comment by darbyjohnston** [comment]
I've fixed the labels and this will be included with the next release.
