### ISSUE TITLE
DJV 2.0.5 - Aspect ratios should have the notation "2.39:1"

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#209]
DO:
- MENU > IMAGE > IMAGE CONTROLS > TRANSFORM

HAPPEN:
- ASPECT RATIO shows i.e. "1.85"

![AspectRatiosColons](https://user-images.githubusercontent.com/9915206/73870105-bf73b600-484b-11ea-9dd6-b45f48f0f7fa.png)

SHOULD:
- ASPECT RATIO shows i.e. "1.85:1"

NOTES:
- this is the standard convention unless something like "16:9" (= "1.78:1") is used
- I do understand what "Native" (native source aspect) means, but what is "Default" and what is it good for?

Side-note: 
"2.35" is often used, but not really a standard. Nowadays "2.39:1" is a kind of a standard wording for "widescreen".

**Comment by darbyjohnston** [comment]
Yeah, "Default" is not a good name for that option. The option uses the pixel aspect ratio in the file and scales the image accordingly, probably the mode most people would expect as the default. Maybe "Scaled"?

**Comment by aberkl** [comment]
> Yeah, "Default" is not a good name for that option. The option uses the pixel aspect ratio in the file and scales the image accordingly, probably the mode most people would expect as the default. 

Okay, starts to make sense to me.
> Maybe "Scaled"?

What about "From file"? And "Native" probalby should be "Unscaled" or "Raw"?

**Comment by darbyjohnston** [comment]
I've fixed the labels and added an option for 2.39:1, this will be included with the next release.
