### ISSUE TITLE
DJV 2.0.5 - Image Controls: COLOR related paramerters cluttered over several tabs

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#210]
DO:
- MENU > IMAGE > IMAGE CONTROLS

HAPPEN:
- COLOR, LEVELS, EXPOSURE, SOFT CLIP have separate tabs

![ImageControls](https://user-images.githubusercontent.com/9915206/73878575-12089e80-485b-11ea-9fff-fce38d2037a0.png)

SHOULD:
- Be available as one tab since you fiddle with colors in general. Since they all interact to a final "grading" it would be much more efficient to have them grouped.

NOTES:
-  Additionally every parameter should offer not only a "reset" (as already implemented with the "X"), but also a momentary PARAMETER OFF, plus a GLOBAL "GRADE ON/OFF" to toggle the effect of your "grading"

In my opinion this is a good example from kdenlive:

![ColorParams](https://user-images.githubusercontent.com/9915206/73879821-67de4600-485d-11ea-900a-1249cb9cf0e3.png)

**Comment by darbyjohnston** [comment]
I've split out the toggles for the image controls into a separate issue:
https://github.com/darbyjohnston/DJV/issues/238
