### ISSUE TITLE
DJV 2.0.5 - COLOR PICKER region unclear

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#211]
DO:
- MENU > TOOLS > COLOR PICKER

HAPPEN:
- adjustable figure unclear: Does "64" mean a 64x64 square or rater 8x8 = 64?

![ColorpickerRegion](https://user-images.githubusercontent.com/9915206/73882504-7d09a380-4862-11ea-93b1-a192c28f8506.png)

SHOULD:
- be clear using an appropriate label

NOTES:
- since I can set the value to non-square numbers I assume it means 64x64 for the above example

**Comment by darbyjohnston** [comment]
Yes, it's the width/height of the sample area. In addition to using an appropriate label it would be nice if the actual area was visualized around the cursor.

**Comment by aberkl** [comment]
> Yes, it's the width/height of the sample area. In addition to using an appropriate label it would be nice if the actual area was visualized around the cursor.

Just a thought:

![PickerArea01](https://user-images.githubusercontent.com/9915206/73919151-4adc5e00-48c3-11ea-9dd3-9a25ce720b52.png)

I would suggest not to visualize the area (which can be very small) but the position by using a cross-hatch.

**Comment by darbyjohnston** [comment]
On second thought I think this would be better in the tooltip; once you discover the meaning I don't think it's really necessary to see the label all of the time. How about extending the tooltip to something like: "Set the size of the color picker sample. The color picker sample is a square with the cursor at the center."

**Comment by aberkl** [comment]
> On second thought I think this would be better in the tooltip; once you discover the meaning I don't think it's really necessary to see the label all of the time. How about extending the tooltip to something like: "Set the size of the color picker sample. The color picker sample is a square with the cursor at the center."

Yes, the tooltip seems to make sense. Shorter and imho with more information it could be "Size of the color picker: [width] x {height] pixels."
