### ISSUE TITLE
DJV 2.0.5 - Numeric values should be adjustable by mouse-wheel

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#212]
DO:
- i..e. MENU > TOOLS > COLOR PICKER
- try to adjust numeric value not using numeric input or slider

HAPPEN:
- not possible

![AdjustNumeric](https://user-images.githubusercontent.com/9915206/73883276-f2c23f00-4863-11ea-950e-1ce1f4e08d6d.png)

SHOULD:
- when hovering numeric value or slider a MOUSE WHEEL TURN would be very intuitive

NOTES:
- probably more important when it comes to color fiddling in IMAGE CONTROLS

**Comment by aberkl** [comment]
In other words: As was possible with DJV 1.x

**Comment by darbyjohnston** [comment]
I checked in the changes for this and it will be available with the next release. If you hover over a numeric value or slider and turn the mouse wheel then that widget will take the text focus (orange outline). While the widget has text focus the scroll wheel can be used to change it's value.
