### ISSUE TITLE
DJV 2.0.5 - MARK IN/OUT and GOTO IN/OUT have identical icons

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#214]
DO:
- open any clip

HAPPEN:
- MARK IN/OUT and GOTO IN/OUT have identical icons

![MARK_vs_GotoMARK](https://user-images.githubusercontent.com/9915206/74103846-be929b00-4b4f-11ea-8897-ab47f2077d0c.png)

SHOULD:
- different icons since different functions

NOTES:
- on the bottom of the image I added a suggestion

**Comment by darbyjohnston** [comment]
I've modified the icons and they will be included with the next release.
