### ISSUE TITLE
DJV 2.0.5 - cannot open more than 1 file from File Open requester

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#215]
DO:
- FILE > OPEN
- try to select more than 1 file to open (commonly by SHIFT + SELECT multiple files)

HAPPEN:
- not possible

SHOULD:
- be possible

**Comment by darbyjohnston** [comment]
Hi, I've added this and will include it with the next version; you can now use shift+click and ctrl+click to select multiple files to open in the file browser and recent files dialog.
