### ISSUE TITLE
DJV 2.0.5 - individual windows may be moved "underneath" menu bar

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#216]
DO:
- un-maximise
- move a window topmost

HAPPEN:
- window top partly hidden underneath main menu bar

![HiddenUnderbar](https://user-images.githubusercontent.com/9915206/74156052-ddf3fb80-4c15-11ea-9e84-7cd461f92774.png)

SHOULD:
- not be hidden

NOTES:
- left, right and bottom have a "padding" that does not allow to go to the very edge - which seems reasonable

**Comment by darbyjohnston** [comment]
I've made a couple large UI changes that prevent this from happening now:
* The menu bar and timeline don't overlap the image anymore (https://github.com/darbyjohnston/DJV/issues/355).
* I removed the MDI canvas (the multiple windows feature) and replaced it with a single view and a new dialog to quickly switch between clips (https://github.com/darbyjohnston/DJV/issues/346). This does remove the ability to compare clips side by side, but arguably the MDI canvas wasn't a great solution to that anyway and what is needed is an actual A/B system (https://github.com/darbyjohnston/DJV/issues/24).
