### ISSUE TITLE
DJV 2.0.5 - no longer possible to select another window with PGUP/PGDOWN after TAB

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#218]
DO:
- open 2 clips
- verify PGUP/PGDOWN toggles focus between the 2 windows
- press TAB

HAPPEN:
- active window sets focus on "The current frame" field
- PGUP/PGDOWN no longer toggles focus between the 2 windows

SHOULD:
- be possible to exit "The current frame" field and return to toggle between the windows using PGUP/PGDOWN

**Comment by darbyjohnston** [comment]
Hi, when you press tab or shift+tab, the keyboard focus is moved to the next widget that can accept the focus (designated by the orange outline). When a widget has keyboard focus it has priority over the keys, in this case the current frame widget uses page up/page down to jump ahead/back 10 frames. To clear the keyboard focus press the escape key and the shortcuts will work again.

**Comment by aberkl** [comment]
> To clear the keyboard focus press the escape key and the shortcuts will work again.

Okay, fair enough, maybe ESC is to obvious. 

But wouldn't it make sense to loose/release widget focus (here: "The current frame") when clicking the other window?

**Comment by darbyjohnston** [comment]
Good point, maybe to expand on that clicking anywhere should release the text focus.

**Comment by darbyjohnston** [comment]
I've made a change so that clicking anywhere (like the other window) will release the text focus and allow shortcuts to work again. This is combined with the fix for:
https://github.com/darbyjohnston/DJV/issues/217
