### ISSUE TITLE
Menu area overlap produces blink

### ISSUE THREAD

**Issue by PiOverFour** [darbyjohnston/DJV#223]
When placing the mouse exactly between two menu items, there is a 1px area where they are both activated and blink. This results in this effect (epilepsy alert):
![menu](https://user-images.githubusercontent.com/6894749/74733840-79582280-524d-11ea-99ba-cbde22efd069.gif)

**Comment by darbyjohnston** [comment]
Thanks, I just noticed that as well.

**Comment by darbyjohnston** [comment]
OK, this should be fixed now.
