### ISSUE TITLE
Scrub as in previous DJV viewer 

### ISSUE THREAD

**Issue by SheepDomination** [darbyjohnston/DJV#224]
![DJVprevious](https://user-images.githubusercontent.com/6827459/74801457-a552c280-52a4-11ea-9726-70fb645395b1.jpg)

I would like to see as was the previous version of DJV view the toolbar where one can scrub though the frames ?

**Comment by darbyjohnston** [comment]
Hi, as I mentioned in the previous thread I have already created an issue for this (https://github.com/darbyjohnston/DJV/issues/175), I'm closing this one as a duplicate.
