### ISSUE TITLE
DJV 2.0.5 - Actual playback speed not displayed correctly if 240 FPS

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#226]
DO:
- load any clip
- set playback speed to 240

HAPPEN:
- playback speeds up but actual playback speed remains at around 24 FPS:

![HighSpeed](https://user-images.githubusercontent.com/9915206/75069377-56e63380-54f1-11ea-8887-a3feedb1f4a9.png)

SHOULD:
- show actual playback speed

NOTES:
- seems to work okay for 120 FPS

**Comment by darbyjohnston** [comment]
Hi, do you have the "Play every frame" option enabled in the speed menu?

**Comment by aberkl** [comment]
> Hi, do you have the "Play every frame" option enabled in the speed menu?

No, I haven't

**Comment by darbyjohnston** [comment]
What kind of media were you playing back? It seems to work OK for me with image sequences and some movies, other movies I am getting the wrong FPS, though I'm getting half speed (120), not 24.

**Comment by darbyjohnston** [comment]
This should be mostly fixed, though there does need to be a minimum number of frames to playback. The current minimum is set to 30.
