### ISSUE TITLE
Sequences not detected, even with the Auto-detect setting

### ISSUE THREAD

**Issue by PiOverFour** [darbyjohnston/DJV#230]
Hi,
I tried to open a file sequence with:
```
djv my_seq.*.exr
```
or
```
djv my_seq.0001.exr my_seq.0002.exr my_seq.0003.exr
```
but only the first frame is displayed. The playback interface does not appear either. It does have an effect however, because when the option is disabled, the first 16 images are loaded individually, as specified in #174.

**Comment by darbyjohnston** [comment]
Hi, thanks for reporting the issue; I just tried this and it seems to work OK for me. When the option is enabled both of the command line examples you gave open the entire sequence. When the option is disabled the files are opened individually. The playback interface doesn't appear for individual images. Just checking, are you using the latest source from GitHub?

**Comment by PiOverFour** [comment]
I found out that it works when the sequence is not in the working directory, or when specifying an absolute path.
So actually,
```
djv /tmp/my_seq.*.exr
cd /tmp && djv ./my_seq.*.exr
```
both work, but
```
cd /tmp && djv my_seq.*.exr # no "./" before seq
```
doesn’t.
I am using the latest sources.

**Comment by darbyjohnston** [comment]
I was using an absolute path for my test, I wonder what the difference is... I'll check it out, thanks!

**Comment by darbyjohnston** [comment]
OK, this should be fixed now and will be included with the next release.
