### ISSUE TITLE
Feature request: Additional decoder support for mepg2

### ISSUE THREAD

**Issue by VuiMuich** [darbyjohnston/DJV#235]
Hi,
first of all thanks for the great work, the DJV2 release are great!

If I'm not under a wrong impression you have a full ffmpeg under the hood right?
So I was wondering, why there is not, or there could be deciding support for mpeg2.
I feel this codec has not lost in relevance completely, especially in media playback servers and event AV suits. In such environments a universal player for checking files prior importing to the show system might be handy and we love that DJV enables us to check HAP encoded files. Though for mepg2 (in our cases mostly .m2v containered elementary stream files) we are required to keep VLC still at hand.

Bests,
Johannes

**Comment by darbyjohnston** [comment]
Hi, yes, DJV uses the LGPL version of FFmpeg for movie file support. There shouldn't be any problem enabling MPEG2, I probably just didn't add the file extension for it. I'll add the ".m2v" file extension, are there any more?

**Comment by VuiMuich** [comment]
Thanks.
Maybe the other flavors of mpeg2 containers like .mpeg .mpg .ts .ps .vob etc.

**Comment by darbyjohnston** [comment]
OK, I've added the various extensions and will include this with the next release.
