### ISSUE TITLE
Feature Request: Alpha Checker Background

### ISSUE THREAD

**Issue by VuiMuich** [darbyjohnston/DJV#237]
For Playback of clips with alpha channel a option to have the commonly used alpha checker board background could be helpful.

**Comment by darbyjohnston** [comment]
Seems reasonable, I recently added this for the color swatches in the color picker. Would you want to control the size of the checker board?

**Comment by VuiMuich** [comment]
not necessarily, maybe have the scale linked to the "UI scale"/DPI settings?

**Comment by darbyjohnston** [comment]
Hi, I've added this feature and will include it with the next release.

![DJV Background Checkers](https://user-images.githubusercontent.com/8532558/83314152-e0329380-a1cd-11ea-9c5d-5f8b66ec580a.PNG)
