### ISSUE TITLE
"iCCP: known incorrect sRGB profile" on certain PNG files

### ISSUE THREAD

**Issue by LewisOrton** [darbyjohnston/DJV#239]
It seems like the problem reported [here ](https://sourceforge.net/p/djv/bugs/58/)before is happening again in the latest version.

![image](https://user-images.githubusercontent.com/9100561/76472698-39203600-63ee-11ea-9bd9-afb2e0ea80fd.png)

**Comment by darbyjohnston** [comment]
Hi, this should be fixed now and will be included with the next release.
