### ISSUE TITLE
Recent files path is relative

### ISSUE THREAD

**Issue by PiOverFour** [darbyjohnston/DJV#241]
When opening a file sequence from the command line with a relative path, this path is saved as is to the recent files, leading to the file being impossible to open if DJV is not called from the same directory. The path should be translated to absolute before saving.

![image](https://user-images.githubusercontent.com/6894749/76952649-b1ff2080-690d-11ea-9fff-4da61fe2e3cd.png)

**Comment by darbyjohnston** [comment]
Hi, thanks for finding this, I just checked in a fix and will include it with the next release.
