### ISSUE TITLE
Integer Frame number display

### ISSUE THREAD

**Issue by deshudiosh** [darbyjohnston/DJV#246]
I'd love to have an option to display current frame number as flat integer, not time-formatted.
It may be added next to the time stamp:

![image](https://user-images.githubusercontent.com/19651485/77854499-0b5b2f80-71eb-11ea-8a33-d9016363f785.png)

**Comment by PiOverFour** [comment]
This is possible if you use Frames as time units (Settings → General → Time → Units: Frames).
You can’t currently have both, though.

**Comment by deshudiosh** [comment]
Thanks, I missed it somehow.

**Comment by aberkl** [comment]
Having both frame number and timecode actually would be nice.

**Comment by Abdull** [comment]
> This is possible if you use Frames as time units (Settings → General → Time → Units: Frames). You can’t currently have both, though.

Documentation: https://darbyjohnston.github.io/DJV/djv_playback.html#TimeUnits
