### ISSUE TITLE
openexr-patch.tar.gz is corrupt

### ISSUE THREAD

**Issue by kdt3rd** [darbyjohnston/DJV#248]
When I clone the djv repo, and attempt to build, the patch for openexr is failing saying that it is corrupt. It appears to not be a gz tar, even though the file extension says so, and then is incomplete, a tar directory shows a cmakelists.txt file and then gets tar i/o errors.

I also notice that it is still based on OpenEXR 2.3. For 2.4 I fully rewrote the EXR cmake system to be "modern" cmake, and the top level is actually a super build project, but you should be able to just use the external project stuff directly into ilmbase and openexr without specifying as much as you are. Have you made an attempt at this yet? If not, then let me know and I'll attempt to make up a patch and send a PR.

**Comment by darbyjohnston** [comment]
Hi, good catch! It looks like it's actually an uncompressed tar file and I accidentally renamed it with a .gz file extension:
```
file *.gz
openexr-patch.tar.gz: POSIX tar archive (GNU)
otio-patch.tar.gz:    gzip compressed data, last modified: Tue Aug 13 07:39:07 2019, from Unix
```

I'm curious what system you are running? Somehow this has magically worked on all of my build machines.

If you have any bandwidth to try to upgrade DJV to OpenEXR 2.4 that would be great; it's something I've been meaning to do but haven't had the time for. I would love to get rid of my custom patch as well, most of it is CMake tweaks that are probably obsolete with the work you have done on 2.4. The only code change in the patch is a fairly obscure bug fix which I need to make a pull request for.

In the meantime I'll check in a quick fix for the corrupt patch.

Thanks, Darby

**Comment by darbyjohnston** [comment]
I just checked in a fix to make the patch a proper .tar.gz file.

**Comment by kdt3rd** [comment]
I'm running arch linux, both tar and bsdtar end up seeing I/O errors:

```
% tar tvf third-party/openexr-patch.tar.gz 
drwxrwxr-x darby/darby       0 2019-05-29 06:46 ./
-rwxrwxr-x darby/darby    7307 2019-05-29 06:39 ./CMakeLists.txt
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

**Comment by kdt3rd** [comment]
although your new version seems just fine - thanks for that! It looks like it is still failing as it looks like the external project stuff is still finding the exr 2.4 bits I have installed locally, and getting some import errors or somesuch, still parsing the build log.

I will try to work up a patch to update to exr 2.4, although may take a week or two

**Comment by darbyjohnston** [comment]
If you post the build log I would be happy to take a look as well; I'm a bit surprised it's picking up the other version, the DJV CMake files are hard-coded to use the versions within the build directory.

**Comment by darbyjohnston** [comment]
Hi Kimball, just wanted to check if you had any time to look into upgrading DJV to OpenEXR 2.4? No worries if you haven't, I might take a crack at it since it would be nice to include with the next release.

Thanks, Darby

**Comment by kdt3rd** [comment]
Heya, I just sent in a PR, it works for me under linux, but I don't have other platforms to test on...
