### ISSUE TITLE
feature request : OpenEXR / Switch between AOVs and read metadatas

### ISSUE THREAD

**Issue by victorpajot** [darbyjohnston/DJV#251]
Hello
Thanks for all the work you do and have done so far.

I'm using DJV to check my cg renders and i was thinking that it would be nice to have the possibility to switch between openEXR AOV's. Ideally when we tap on a shortcut, a list of all AOVs appear on the screen, you can choose wich one to draw, and it applies for all the sequence.

Fetch and print metadatas would be a great feature too.

Thanks again !

**Comment by darbyjohnston** [comment]
Hi, sorry it's not well documented but you should be able to do this with the current version; you can open up a window that will show you the layers/AOVs from the menu item "File/Layers" (keyboard shortcut: Ctrl+L). This window will show all of the layers available and you can select which one you want to view. There are also menu items/shortcuts for going to the next/previous layer, "File/Next Layer" (keyboard shortcut: Ctrl+Equal), and "File/Previous Layer" (keyboard shortcut: Ctrl+Minus).

![DJV Layers](https://user-images.githubusercontent.com/8532558/80521108-4f9f3400-893f-11ea-8b1a-c3a52964d63c.PNG)

For metadata you can use the "Information" tool available from the menu item "Tools/Information" (keyboard shortcut: Ctrl+I).

![DJV Info](https://user-images.githubusercontent.com/8532558/80521138-59289c00-893f-11ea-8f56-db52829f81ca.PNG)

**Comment by darbyjohnston** [comment]
For the metadata, currently DJV is only parsing the OpenEXR "standard attributes" like comments, aperture, ISO, etc. We should expand this to include any attributes that have types we can parse, such as strings, floats, vectors, etc.

**Comment by darbyjohnston** [comment]
I split out the support for additional metadata into a separate issue:
https://github.com/darbyjohnston/DJV/issues/252
