### ISSUE TITLE
Image colour correction applied before OCIO?

### ISSUE THREAD

**Issue by mattebb** [darbyjohnston/DJV#263]
Hi,

I'm using DJV with an ACES OCIO config, looking at a float16 OpenEXR file in ACEScg colour space. I wanted to expose down my image to reveal highlight detail but it looks like the image colour correction is applied after conversion to display space?

Ideally all colour correction should be applied in scene-referred linear space, before any display conversion (which will clip).

Maybe this is a separate request, but the colour picker should also always show the original floating point values before view colour corrections are applied.

I've attached a comparison between DJV (incorrect) and Houdini's mplay (correct).

![djv_exposure](https://user-images.githubusercontent.com/1897197/82529693-eea1ff00-9b7e-11ea-96cc-2dc075f3358e.png)
![mplay_exposure](https://user-images.githubusercontent.com/1897197/82529697-f19cef80-9b7e-11ea-8b2e-e93830fb7bb2.png)

Thanks!

**Comment by darbyjohnston** [comment]
Hi, thanks for the bug report, I actually just fixed this and will include it with the next release:
https://github.com/darbyjohnston/DJV/issues/253

For the color picker, do you mean show the color values without the exposure settings applied?

**Comment by mattebb** [comment]
Amazing, thankyou very much!

And yes, it would be best to show the un-adjusted values (or at least have a setting to 1choose which). For example if you're exposing down or up to try and see details so you can inspect the values, you generally want to be seeing the original values, to know what's actually in your file. 

cheers

**Comment by darbyjohnston** [comment]
That makes sense, I'll add an option for that as well as an option for toggling whether the color space is applied, I could definitely see use cases for each. I've created a new issue for that:
https://github.com/darbyjohnston/DJV/issues/265
