### ISSUE TITLE
Use ⌘ symbol for menu shortcuts on MacOS

### ISSUE THREAD

**Issue by tiltX** [darbyjohnston/DJV#272]
On MacOS, the playback menu is quite wide because many of the shortcuts are prefixed with "Command+". I've tried adding the symbol that MacOS uses (⌘) to the text files but it doesn't show up. Maybe it's a font issue?

The symbol, according to https://apple.stackexchange.com/questions/4074/what-do-i-type-to-produce-the-command-symbol-in-mac-os-x is the unicode "place of interest" icon.

**Comment by darbyjohnston** [comment]
Hi, it looks like you are right, the font bundled with DJV doesn't have ⌘. How about abbreviating "Command" to "Cmd"?

**Comment by darbyjohnston** [comment]
I found the ⌘ symbol in a separate font, "Noto Sans Symbols2", here is a before and after screenshot. The symbols are not as nice looking as the macOS system font, but it does make the menu more narrow.

Before:
![DJV Playback Menu Text](https://user-images.githubusercontent.com/8532558/83828435-84687e80-a695-11ea-9af7-4b7f9c5eaecb.png)

After:
![DJV Playback Menu Symbols](https://user-images.githubusercontent.com/8532558/83828460-95b18b00-a695-11ea-91a4-aebffa52f9d2.png)

**Comment by tiltX** [comment]
This looks nice! Thank you.
