### ISSUE TITLE
Error Incomplete file reading TGA sequence

### ISSUE THREAD

**Issue by MrLacpierre** [darbyjohnston/DJV#273]
I can't read TGA sequence anymore with the latest update. It says that the files are incomplete.
The TGA files can be read in Photoshop and I could read it witj djv a few months ago.

**Comment by darbyjohnston** [comment]
Hi, I am able to view TGA sequences with the latest release, could you send me more information about the issue? Like the exact error message, how the files are names, and an example image if you can share one.

**Comment by darbyjohnston** [comment]
Probably fixed with:
https://github.com/darbyjohnston/DJV/issues/277

**Comment by darbyjohnston** [comment]
Closing this since I believe it was fixed with https://github.com/darbyjohnston/DJV/issues/277, and never received any sample images...
