### ISSUE TITLE
TGAs not playing

### ISSUE THREAD

**Issue by hyperfx** [darbyjohnston/DJV#277]
I'm using DJV 2.0.6 and finding that TGA image sequences are giving me an error and not playing.

I'm attaching the System Log text file and a link to download a short TGA sample sequence

I'm using Win 7, dual x5650 procs, 108G ram, Titan X card

https://www.dropbox.com/s/02khnug3tyo7c41/ec110.04FG.v01.TGAs.zip?dl=1

[DJV_TGA_not_playing_system_log.txt](https://github.com/darbyjohnston/DJV/files/4749854/DJV_TGA_not_playing_system_log.txt)

**Comment by darbyjohnston** [comment]
Hi, thanks for the log and test images, I took a quick look and found a pretty serious bug in the TGA code when reading compressed images. It should be fixed now and I will include the fix with the next release.

**Comment by NNois** [comment]
Hi could you reopen the case ? in 2.0.8 i can't read ALL my tga files, here is a sample (with alpha)
[tga_image_file.zip](https://github.com/darbyjohnston/DJV/files/13447546/tga_image_file.zip)
