### ISSUE TITLE
TGAs may still be broken

### ISSUE THREAD

**Issue by hyperfx** [darbyjohnston/DJV#286]
Thanks for hitting it so quickly! 

I tested 2.0.7 on my machine with the test TGAs I sent you earlier, and it worked. I tired with some other TGAs, and it worked. Then I tried with these TGAs (and some others), and it did not work. So figured I'd pass it along. 

https://www.dropbox.com/s/24h98p64jmd953r/DJV_test_TGAs_2.zip?dl=1

[TGA_bug_2_system_log.txt](https://github.com/darbyjohnston/DJV/files/4762535/TGA_bug_2_system_log.txt)

**Comment by aberkl** [comment]
Sequence plays fine in DJV 1.3.0, not in 2.0.6.

**Comment by darbyjohnston** [comment]
Hi, thanks again for the log and test files, I just checked in a fix and will include this with the next release.
