### ISSUE TITLE
DJV 2.0.7 - libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#287]
I get a message "libm.so.6: version `GLIBC_2.29' not found" on Linux Mint 19.1, DJV 2.0.7 does not start.

This seems to be an issue with other applications as well, see i.e. [here](https://github.com/electron/electron/issues/18181).

No such issues with DJV 2.0.6.

**Comment by tiltX** [comment]
I'm experiencing a similar issue on Centos 7. DJV 2.0.6 worked great but 2.0.7 no longer launches because the system libraries of Centos seem to be too old now. The errors I get are:

```
/usr/local/DJV2/bin/djv: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /usr/local/DJV2/bin/djv)
/usr/local/DJV2/bin/djv: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/local/DJV2/bin/djv)
/usr/local/DJV2/bin/djv: /lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /usr/local/DJV2/bin/djv)
/usr/local/DJV2/bin/djv: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/local/DJV2/bin/djv)
/usr/local/DJV2/bin/djv: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/DJV2/bin/djv)
/usr/local/DJV2/bin/djv: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/local/DJV2/bin/djv)
/usr/local/DJV2/bin/djv: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/local/DJV2/bin/djv)
/usr/local/DJV2/bin/djv: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /usr/local/DJV2/lib/libavcodec.so.58)
/usr/local/DJV2/bin/djv: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/DJV2/lib/libavdevice.so.58)
/usr/local/DJV2/bin/djv: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /usr/local/DJV2/lib/libavfilter.so.7)
/usr/local/DJV2/bin/djv: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /usr/local/DJV2/lib/libavformat.so.58)
/usr/local/DJV2/bin/djv: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/DJV2/lib/libavformat.so.58)
/usr/local/DJV2/bin/djv: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/DJV2/lib/libavutil.so.56)
```

**Comment by darbyjohnston** [comment]
Guess I shouldn't have upgraded my Linux workstations! I'll try spinning up some VMs with older versions and compile a new release.

**Comment by darbyjohnston** [comment]
I just uploaded a new release, 2.0.8, that should fix this; you can download the new packages here:

https://darbyjohnston.github.io/DJV/download.html

**Comment by ruchitinfushion** [comment]
Thanks, 2.0.8 is working fine on CentOS 7.8

**Comment by aberkl** [comment]
> Thanks, 2.0.8 is working fine on CentOS 7.8

Same here with Linux Mint 19.1. Thanks for the quick fix!

**Comment by nrusch** [comment]
Just wanted to note that this issue still exists for CentOS 7.7. Let me know if you'd like me to open a new issue for it, or if you consider it "wontfix" at this point.

If the latter, and/or if a minimum OS version is actually a hard requirement, it would be great to have that documented somewhere.

Thanks!

**Comment by darbyjohnston** [comment]
I'm OK with supporting earlier CentOS versions as long as they are forward compatible with the latest version. Though out of curiosity why not upgrade from 7.7 to 7.8?

**Comment by tiltX** [comment]
Curiously, DJV 2.0.8 works fine on our Centos 7.7 machines. I'm not aware that I have installed anything out of the ordinary.

**Comment by nrusch** [comment]
AFAIK the only (backwards-) compatibility break in the CentOS 7 line was between 7.3 and 7.4. I am not aware of any forwards-compatibility issues.

> Though out of curiosity why not upgrade from 7.7 to 7.8?

In short, because upgrading OSes for an entire studio that is in fairly heavy production without breaking things is a bit involved... We are planning to upgrade to 7.8, but we don't know exactly when that will fit into the timeline vs. some of the other infrastructure tasks ahead.

**Comment by nrusch** [comment]
Just to clarify, we are not reliant on DJV, so this isn't a major impediment. However, it would be great to be able to make it available to artists as an option, and even better to be able to keep it up to date. :)

I haven't tried building DJV from source yet, but we don't really have time to go down that road at present.

**Comment by darbyjohnston** [comment]
Just for reference I created a new issue to document the supported OS versions:
https://github.com/darbyjohnston/DJV/issues/334

**Comment by elielgvs** [comment]
Is there possible to view the timeline in frames (0000) and not in seconds (hh:mm:ss)?

**Comment by darbyjohnston** [comment]
@elielgvs, you can change the time units in the settings (check out the screenshot).
![DJV Time Units](https://user-images.githubusercontent.com/8532558/112530344-9110ad00-8d63-11eb-9389-d87045a998a4.png)

**Comment by bvz2000** [comment]
I am also running CentOS Linux release 7.9.2009 (Core) and am getting the same issue:

bin/djv: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by bin/djv)
bin/djv: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by bin/djv)
bin/djv: /lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by bin/djv)
bin/djv: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by bin/djv)
bin/djv: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by bin/djv)
bin/djv: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by bin/djv)
bin/djv: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by bin/djv)
bin/djv: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by lib/libavcodec.so.58)
bin/djv: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by lib/libavformat.so.58)
