### ISSUE TITLE
DJV fails to load image sequence if "start at the first frame" is off

### ISSUE THREAD

**Issue by tiltX** [darbyjohnston/DJV#292]
DJV won't start with an image sequence argument if "start at the first frame" is disabled. The error printed on the console is "ERROR: stoi".

How to reproduce:

- open DJV without any other command line arguments and disable the "start at the first frame" option in the settings panel. 
- close DJV
- start DJV with a file sequence on the command line that contains a placeholder for the frame numbers (for example djv /path/to/images.####.jpg)
- open DJV without arguments and enable "start at the first frame", then start it again using the file sequence as an argument. Now, everything works as expected.

I'm running DJV 2.0.8 on Linux.

**Comment by darbyjohnston** [comment]
Hi, thanks for reporting this, I just checked in a fix and will include it with the next release.
