### ISSUE TITLE
OCIO configuration given by command-line argument shouldn't be remembered

### ISSUE THREAD

**Issue by tiltX** [darbyjohnston/DJV#293]
I've tried to write a script that starts djv to play back exr renders with a project-specific ocio configuration, display and view. Sometimes, the view might simply be sRGB but for other projects, I want to use a film LUT for example.

The logic to figure this out is of course outside of djv's domain. But the problem I'm running into is that the values I've specified on the command-line using -ocio_config, -ocio_view and so on will be used as defaults for subsequent invocations of djv.

Would it be possible to only save the OCIO configuration if it has been switched using the colorspace widget? That way, command-line arguments could serve as an override while simply launching "djv" on its own would use the default OCIO configuration and colorspaces.

**Comment by darbyjohnston** [comment]
I can see how this would be useful, it seems like this should apply to other command line flags as well?

**Comment by darbyjohnston** [comment]
OK. I think this is working now, I've made some changes so that the OCIO command line arguments will temporarily override the settings instead of changing them. I'll include this with the next release.

**Comment by tiltX** [comment]
sounds great! Thank you.
