### ISSUE TITLE
Can't open flies with a date as the filename

### ISSUE THREAD

**Issue by thompsonalt** [darbyjohnston/DJV#294]
**Environment:**
Windows 10 / DJV 2.0.6

**To reproduce:**
Rename an mp4 file "12-25-01.mp4". Try to open the file with DJV. (By double clicking if DJV is set as the default program, or by dragging the file into DJV. 
_Note: Using [File > Open] inside DJV works as expected._ 

**Result**
Returns an error:
"ERROR: C:\Users\username\Desktop\12-25.mp4: No such file or directory"
Notice it's missing the last "-01" part of the filename. I expect it's because something in the logic to detect image sequences is broken. 

![image](https://user-images.githubusercontent.com/1726762/84608595-cacd9280-ae78-11ea-9862-7b3a9ae82d42.png)

I took a look through the issues and found [this closed one](https://github.com/darbyjohnston/DJV/issues/3) that's similar but not the same.

 Thanks for all the work on DJV! It's always a joy to use.

**Comment by darbyjohnston** [comment]
Hi, thanks for the bug report; could you try this with the latest version, 2.0.8? There are a couple of fixes for file sequences in the new version. You can download it here:
https://darbyjohnston.github.io/DJV/download.html

**Comment by thompsonalt** [comment]
Ah sorry, didn't realize I had an outdated version. That works now!
