### ISSUE TITLE
DJV 2.0.8 - Playback "ping-pong" plays "loop"

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#295]
DO:
- load any clip
- (maybe set an IN and OUT point at characteristic images)
- play "ping-pong"

HAPPEN
- seems to play "ping-pong" only once, then falls into "loop"

SHOULD:
- "ping-pong"

NOTES:
- there seems to be a small difference in "real loop" and "ping-pong"

**Comment by darbyjohnston** [comment]
Is this with movie files or image sequences? Reverse movie playback still needs to be fixed so "ping-pong" currently doesn't work with movies:
https://github.com/darbyjohnston/DJV/issues/152

**Comment by aberkl** [comment]
It was a movie file.

**Comment by darbyjohnston** [comment]
OK thanks, I'm going to close this as a duplicate then.
