### ISSUE TITLE
Command line option to specify "speed" appears to be limited to integers?

### ISSUE THREAD

**Issue by stevetwist** [darbyjohnston/DJV#298]
I'm trying to use the command line "-speed" option, on Windows 10 (DJV 2.0.8), to set the frame rate based on the image sequence being loaded. However, it appears if I specify a floating point frame rate (e.g. "-speed 23.98") it gets truncated to an integer (once loaded, DVJ shows a "custom" frame rate of 23).

Am I doing something wrong? Is it possible to support floating point frame rates on the command line, please?

Thanks!

**Comment by darbyjohnston** [comment]
Hi, thanks for the bug report, this should be fixed now and will be included with the next release. It won't accept arbitrary floating point frame rates, but will recognize common frame rates like 23.98.

**Comment by stevetwist** [comment]
Hi, that's great, thank you. Thanks for the rapid turn around!
