### ISSUE TITLE
A file with a trailing "-" in the name before extension does not get opened

### ISSUE THREAD

**Issue by craGato** [darbyjohnston/DJV#3]
System is Windows 10 Pro x64 1803

This file name opens just fine: 
Blink of an eye - Slow Motion.mp4
![imagen](https://user-images.githubusercontent.com/36661754/48350650-2bd32a00-e688-11e8-9ee1-c27a7fb162f9.png)

This does not (there is a duplicated file extension): 
Blink of an eye - Slow Motion-.mp4
![imagen](https://user-images.githubusercontent.com/36661754/48350766-7c4a8780-e688-11e8-9f4f-566b4dc5f0dc.png)

Other than that DJV is awesome. Just as an additional request (this is just a personal preference). Would it be possible to make left  and right cursor arrows the default next and previous frame. I always have to go to settings and change the default mapping, because each new version writes its own registry keys. I rarely move the frame (ctrl+left and ctrl+right do this on my settings) :). 

Keep up the good work!!!
Cheers

**Comment by darbyjohnston** [comment]
Hi,

Thanks for the bug report! That should be easy to fix, I think DJV is trying to interpret the trailing '-' as a file sequence and is getting confused.

The keyboard shortcut change sounds good, it seemed like a good idea at the time but I'm not sure I've ever actually used them either. What would you suggest for the up and down keys? Maybe go to the beginning/ending of the clip (or current in/out points)?

Sorry about the preferences resetting, that normally shouldn't happen with every version. I only do that when I make a change to the preferences and unfortunately there have been a number of those lately.

**Comment by craGato** [comment]
What do you think about this mapping?

Just to note, I am big fan of key combinations :)

Right cursor = Playback/Next
Shift + Right cursor = Playback/Next 10
Control + Right cursor = Playback/Next 100
Control + Shift + Right cursor = View/Right (rarely used, almost never used actually)

Left cursor = Playback/Previous
Shift + Left cursor = Playback/Previous 10
Control + Left cursor = Playback/Previous 100
Control + Shift + Left cursor = View/Left (rarely used, almost never used actually)

Here are a more cuestionable shorcuts, now we have the typical J-K-L playback shorcuts present in most video editing software, but for 
me in particular I prefer to have the playback shortcuts as close to each other as possible and because this is not an editing software. 

Would it be possible to add more than 1 shorcut to an action or more than 1 action to a shortcut (kind of a macro)? so we can have the best of both.
Maybe it is too much to wish, but hey, It doesn't hurt to ask :)

Up cursor = forward playback + Playback/Toggle (Houdini like)
Control + Up = Playback/Start (Houdini like) (Home key is good as well because it is next to the cursors)
Control + Shift + Up = View/Up (rarely used, almost never used actually)
Shift + Up = Go to In mark

Down cursor = Reverse playback + toggle playback (Houdini like)
Control + Down = Playback/End (End key is good as well because it is next to the cursors)
Control + Shift +  Down = View/Down (rarely used, almost never used actually)
Shift + Down = Go to Out mark

These is my prefered mapping but may change in the future of course.

Also if I may ask for another thing. 
- Always on top feature - 
I have my own way of keeping any window on top via and Autohotkey script but It would be nice to have this feature built-in as sometimes my co-workers ask how the can do this and i have to install "things" :D

That’s just my two cents.

As always, thanks for your hard work. Cheers

**Comment by darbyjohnston** [comment]
Those seem like reasonable shortcuts, I'll add them for the next major version (1.3.0).

I didn't think that Qt supported multiple shortcuts per action but I just checked the documentation and it turns out they do, I'll see if I can add support for that. The multiple actions per shortcut is an interesting idea, what did you have in mind using it for?

I'll check out the "always on top" feature, I think that's easy to do with Qt.

**Comment by craGato** [comment]
Great! Thanks. About the multiple actions per shortcut, I just thought about that due to the fact that 
 - Up cursor = Forward playback + Playback/Toggle (Houdini like)

for example, involves 2 actions, setting forward playback and toggling the playback too. The same apllies to 
- Down cursor = Reverse playback + Playback/Toggle (Houdini like)

I can't think of any other use right now but I guess it can be useful somehow. But maybe it is not worth the effort if it is hard to implement.

**Comment by NNois** [comment]
I vote for those too ;-)

**Comment by darbyjohnston** [comment]
Hi,

Sorry for the delay! I just uploaded a new version which fixes this issue (1.2.5), you can download it here:
http://djv.sourceforge.net/Download.html

**Comment by darbyjohnston** [comment]
Hi, sorry for the very long delay! I'm closing this issue out since the original bug is fixed. For the other issues that came up:
* In the new 2.0 version the keyboard shortcuts for moving the view have been moved to the numeric keypad, and the arrow keys are now used for playback; left/right for changing the frame, and up/down for forward/reverse/stop playback.
* There is a separate issue for the window stay on top feature: https://github.com/darbyjohnston/DJV/issues/55
