### ISSUE TITLE
Can't open files with unusual characters in filename

### ISSUE THREAD

**Issue by thompsonalt** [darbyjohnston/DJV#301]
DJV fails to open files if the encoding of the filename text is different than what it expects. Or something to that effect? This is probably a niche issue, but I noticed it from the files that the windows screen recorder generates. 

**To reproduce**: put an ® symbol in a filename and try to launch it in DJV through windows.

In this case, file > open and dragging the file into DJV work fine but double clicking or launching the file through windows doesn't. I'm not very familiar with text encoding, but it must be a utf vs unicode issue or something?

**Comment by darbyjohnston** [comment]
Hi, it looks like it was a Unicode issue; something was happening when the strings were passed through the command line that was causing an error. I've switched over to using the Windows "wide" string main entry points and it fixes the issue, I'll include this with the next release.
