### ISSUE TITLE
Can't open image sequence frame01.png - frame80.png

### ISSUE THREAD

**Issue by net147** [darbyjohnston/DJV#306]
Opening image sequence frame01.png to frame80.png fails. It incorrectly detects it as frame1.png - frame80.png and fails to open frame1.png. It was working fine in DJV 2.0.6.

Version: DJV 2.0.8
OS: Linux

**Comment by darbyjohnston** [comment]
Hi, I have not been able to reproduce this; how are you opening the files, drag and drop, file browser, or the command line? Also could you attach the log file as described here:

https://darbyjohnston.github.io/DJV/contributing.html#Bugs

**Comment by net147** [comment]
I am opening using File > Open. I have Enable File Sequences checked under Settings - Miscellaneous in the File Browser settings (it was unchecked by default for some reason).
[djv.log](https://github.com/darbyjohnston/DJV/files/4807215/djv.log)
It is strange. If I copy the directory containing the files to another directory, it works.
Maybe something to do with the order of the file entries when listing a directory during the sequence detection?

**Comment by net147** [comment]
Try this.

Create frame80.png to frame01.png in reverse order in new folder
```console
cd ~
mkdir seq
cd seq
for i in `seq 80 | tac`; do convert -size 320x240 canvas:black $(printf frame%02d.png $i); done
```

Open the folder in DJV using File > Open and navigate to it.

**Comment by darbyjohnston** [comment]
That did it; I checked in a fix and will include it with the next release.
