### ISSUE TITLE
DJV 2.0.8 - only 1st clip plays with audio

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#309]
DO:
- open 1st clip with audio
- verify audio plays -> fine
- open a second clip with audio

HAPPEN
- second clip plays with no audio

SHOULD:
- all clips should play with audio

NOTES:
- 1st clip still plays audio
- even when 1st clip is closed 2nd clip still plays no audio
- closing 2nd clip and re-opening 2nd clip finally gives audio for it
- used to work in DJV 2.0.6

**Comment by darbyjohnston** [comment]
I checked in a fix for this and will include it with the next release. I had switched versions of the audio library I was using for 2.0.8, and went back to the previous one that 2.0.6 used.
