### ISSUE TITLE
DJV 2.0.8 - Some UI elements do not switch language

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#314]
DO:
- change language to i.e. German
- check settings item "Eingang"

HAPPEN
- Geschwindigkeit  "Slow"

![Screenshot from 2020-06-21 16-08-00](https://user-images.githubusercontent.com/9915206/85226744-68751480-b3d9-11ea-9bb6-c0f162eeab41.png)

SHOULD:
- "Langsam"

NOTES:
- similar when switching back to "English": Shows "Langsam", should show "Slow"
- maybe other UI items are also affected?

**Comment by darbyjohnston** [comment]
Good catch; I checked in a fix and will include it with the next release.
