### ISSUE TITLE
Feature request: Support OCIO color conversions when viewing QuickTimes

### ISSUE THREAD

**Issue by stevetwist** [darbyjohnston/DJV#330]
It appears that the use of OCIO configs to control the colorspace configurations only works for image sequences. In my testing (2.0.8, Windows 10, x64) OCIO colorspace settings were ignored when playing back QuickTime files.

It would be very useful for us to be able to apply OCIO colorspace correction to QuickTimes, during playback. We often output QuickTimes in a client requested colorspace which differs from the display colorspace of our artist workstations. Thus, it would be beneficial to be able to view those files correctly on the artist workstations (which we cannot do, currently).

Thanks!

**Comment by darbyjohnston** [comment]
Hi, I just tried here with a ProRes .mov file and it seemed to be working OK. You have color spaces set for both the display and image? In the image section of the "Color Space" window you can specify the color space either as the "Default" or specifically for the "FFmpeg" plugin.

![DJV FFmpeg Color Space](https://user-images.githubusercontent.com/8532558/86629183-de53b100-bf7f-11ea-8ba8-a33013d5fc18.PNG)

**Comment by stevetwist** [comment]
Thanks for the quick reply. That's interesting that it works for you.

I'm having a hard time getting consistent results. 

I've tried using the "Nuke Default" config, and my own custom OCIO config (which works perfectly with image sequences), and both ProRes 4444 and DNxHD formats. I'm setting both the image and the display colorspaces.

In my initial test it did not work (hence submitting the issue). However, as it worked for you, I re-tested it. In some of those tests, it worked as expected, and as you described. Other times, it appeared that my colorspace settings were ignored. Changing them does not update the display. Having said that, I've also just encountered an issue where DJV stops playing back the QT (I click play, the time-slider moves, but the image hangs on the first frame), so now I'm not sure if that is the problem I sometimes am encountering (the colorspace was changing internally but the display was not refreshing), as opposed to an OCIO colorspace problem.

I wish I could diagnose the exact steps that are causing the issue, to provide you with a useful bug report, but it's behaving inconsistently for me. Each time I test it, I get different results. I'm thinking that unless this is an issue for other people, we maybe just ignore that it is an issue for me? We have a work around (which we've used up until this point, anyway), so it isn't a show stopper for us.

Thanks,
Steve

**Comment by darbyjohnston** [comment]
I did some more testing and still haven't been able to reproduce what you are seeing, but I'm actually working on the color space code right now and have been fixing up some parts that looked a bit dodgy. I'll have a new version available in a couple weeks, if you have some time to test it out that would be great.

For the QT file, is it video only (no audio tracks)? I just noticed that movie files without audio tracks don't playback properly, usually getting stuck on the first frame. I've made a separate issue for that:
https://github.com/darbyjohnston/DJV/issues/331

**Comment by stevetwist** [comment]
Hi. Yeah, absolutely, I'll definitely test out the new version when released. If it isn't too much to ask, can you please reply here when it's released? I might miss it, otherwise.

The QTs I'm using are video only, so audio isn't the cause of the issue for me, unfortunately. When the issue occurs I am sometimes able to scrub to a different frame, and eventually the view might update to that frame, but then hangs on that frame instead. I thought maybe my machine was struggling to keep up with the processing - but it's a fairly powerful workstation (6 core i7, 32GB RAM, NVIDIA 770GTX). It seemed to be aggravated by higher bitrate codecs (i.e. the ProRes 4444 file was worse than the DNxHD file - both the same footage, but the ProRes file is about 250MB vs 50MB for the DNxHD)

**Comment by darbyjohnston** [comment]
Thanks, I'll let you know when the new version is available.

Sorry, I meant that QTs without audio tracks are causing the playback issues, I hope to have that fixed in the next version as well.

**Comment by darbyjohnston** [comment]
I'm going to add this to the next milestone and close it as "fixed", we can re-open it later if your testing still shows the problem exists.
