### ISSUE TITLE
'Playback in Loop' does not respect in point

### ISSUE THREAD

**Issue by liljohn360** [darbyjohnston/DJV#349]
When DJV is set to playback in loop, with an in point set, the frames before the in point are still played.

This does not happen when playback mode is set to 'ping-pong', and does not happen when you set the out point to anything before the last frame.

In most cases, VFX shots have a slate frame as the first frame, so it would be useful to be able to set the in point at the second frame in loop mode.

Steps to reproduce:

- Open DJV

- Open an image sequence

- Set the in point to frame 2 (or 1001 in a sequence that starts at 1000)

- Hit play and the slate frame is still displayed despite being before the in point

**Comment by darbyjohnston** [comment]
Hi, thanks for the bug report; which version are you using? I just tried this with the most recent version (2.0.8), and it looked like it was working OK. I opened a sequence with frames 4-100, set the in point to 5, and when it looped it correctly skipped over frame 4.

**Comment by liljohn360** [comment]
I'm using version 2.0.8, on Windows 10 (19041.540)

**Comment by liljohn360** [comment]
I clean re-installed DJV and it works correctly now.
