### ISSUE TITLE
Separate out djvUI?

### ISSUE THREAD

**Issue by michaelquigley** [darbyjohnston/DJV#352]
Was walking through a bunch of the DJV sources... have you ever thought about breaking `djvUI` out as a separate project? Looks like an interesting little UI layer!

**Comment by darbyjohnston** [comment]
Hi Michael, thanks for the interest! I would definitely like to separate out the libraries so they can be used by other applications, both for myself and others who might find them useful. I actually have another GitHub issue for this, so I'm going to close this one as a duplicate, but feel free to to comment on the other issue if you have any more thoughts you would like to add:
https://github.com/darbyjohnston/DJV/issues/232

**Comment by michaelquigley** [comment]
Very nice! Sorry for the duplicate!

**Comment by darbyjohnston** [comment]
No problem at all!
