### ISSUE TITLE
HUD Display Current Filename for Image Sequences

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [darbyjohnston/DJV#354]
In version 1 the HUD would display the full file path for the current frame. With version 2 when I open an image sequence the individual file is not shown, but instead the frame range is. So in v 1 I would get
`\\some\path\frame_0100.jpg`
now I get
`frame_0001-2000.jpg`

There is a 'Frame' display at the bottom, but it displays the timecode, not the frame.

I ask for this because sometimes I really need to know _exactly_ what frame I'm looking at.

**Comment by darbyjohnston** [comment]
Hi, sorry for the delay; if you set the "time units" in the settings to frames it will show the current frame in the HUD instead of the timecode.

![DJV Time Units](https://user-images.githubusercontent.com/8532558/93657518-6a567000-f9e8-11ea-8a79-704dc9397edc.png)

**Comment by Anti-Distinctlyminty** [comment]
Superb, thank you.
