### ISSUE TITLE
Request: Escape Key for Exiting the App

### ISSUE THREAD

**Issue by hced** [darbyjohnston/DJV#357]
An option to have ESC close the app. Makes it faster to just open DJV, check something, then ESC out of it.

**Comment by darbyjohnston** [comment]
Hi, do you know of the current keyboard shortcut "Ctrl+Q" to exit the app? I worry a bit about using the "Escape" key since that is also used to remove text focus from text widgets and to cancel dialogs.

**Comment by hced** [comment]
Got you. I can easily use AutoHotkey to achieve my wish, so no problem.

**Comment by aberkl** [comment]
Slightly off-topic: Once we have **custom shortcuts** back (as in DJV 1.3), we are free to assign any key/key combination to most of the actions.
