### ISSUE TITLE
2.0.8 Reverse Playback is odd when playing H264, MP4

### ISSUE THREAD

**Issue by VogelMoritz** [darbyjohnston/DJV#369]
There are two issue, when reverse playing a video with H264 Codec in MP4 container.
Other codecs and containers are not testes, image sequence is not affected. 

- Reverse playback is faster than forward playback, so it's more like fast-reverse

- while reverse playing, the viewer displays the next frames, instead of the previous frames. When using reverse playback, the video actually fast forwards until reverse playback is stopped. When stopped, it shows the correct frame, though. 

GPU is GTX1080, driver 456.71

[djv.log](https://github.com/darbyjohnston/DJV/files/5531108/djv.log)

**Comment by darbyjohnston** [comment]
Hi, thanks for the bug report and including the log file. I'm working on trying to fix this and hope to include it with the next release; there's an existing issue for this so I'm going to close this one as a duplicate:
https://github.com/darbyjohnston/DJV/issues/152
