### ISSUE TITLE
Portable floatmaps

### ISSUE THREAD

**Issue by Wouterdek** [darbyjohnston/DJV#374]
Hi, thanks for creating/maintaining DJV!

The PFM (Portable FloatMap Image Format) is a file format that is very similar to PPM, but contains 32-bit floating point numbers instead of bytes. It would be nice if DJV supported this, as this file format is both super easy to read/write and supports HDR.
The format consists of a very short header and then just a sequence of binary floats. More details here: [http://www.pauldebevec.com/Research/HDR/PFM/](http://www.pauldebevec.com/Research/HDR/PFM/)

Optionally, there is also [a small extension](https://www.cse.cuhk.edu.hk/~ttwong/data/hdrfire/hdrfire.html) called PF4 which allows for RGBA.

Other applications that support this format include Photoshop, The Gimp, and [TEV](https://github.com/Tom94/tev).

**Comment by darbyjohnston** [comment]
Hi, thanks for the contribution! I actually haven't heard of this file format before but it looks interesting, I like the simplicity of it. I'll take a look at the PR tomorrow.
