### ISSUE TITLE
simple annotations, drawings

### ISSUE THREAD

**Issue by tmdag** [darbyjohnston/DJV#375]
It would be amazing if DJV would have very simple annotation/drawing option.

As a supervisor, I would use such feature the most :)

**Comment by darbyjohnston** [comment]
Hi! Thanks for the feature suggestion, annotations is definitely on the TODO list. There's an existing issue for tracking it here:

https://github.com/darbyjohnston/DJV/issues/117

So I'm going to close this as a duplicate, but feel free to add any other details/comments to the other issue.
