### ISSUE TITLE
OpenEXR Extra Channel Display (AOVs)

### ISSUE THREAD

**Issue by NNois** [darbyjohnston/DJV#4]
Hi,
I'm very glad DJV is on Github !

For many years I wished DJV could display our EXRs coming from 3d renderers. With the possibility to see other channels than Color and Alpha...

Cheers

**Comment by darbyjohnston** [comment]
Hi!

This functionality already exists; open the file menu and look under the "Layer" sub-menu and you should see the additional layers in your file (if they are not showing up it is a bug). You can also use the "Next Layer" and "Previous Layers" menu items to switch layers as well. Here is a screenshot for reference:

![djv file layers](https://user-images.githubusercontent.com/8532558/50172905-f20aca00-02aa-11e9-8ab2-f8d545f065a5.PNG)
