### ISSUE TITLE
memory cache won't work on coded video

### ISSUE THREAD

**Issue by SVAFnemesis** [darbyjohnston/DJV#407]
The single most important reason for me to use DJV is that I can scrub the timeline same way I do it in Adobe Premiere. DJV used to do this flawlessly. As for this update (2.0.7) DJV no longer cache coded video such as h.264, and as a result I can no longer scrub them in timeline. Due to this issue I have no choice but to revert back to the old version, I hope this will be fixed in the future update.

**Comment by darbyjohnston** [comment]
Hi, sorry about the memory caching, I hope to have it fixed in the next version. I already have an existing issue for that so I'm going to close this as a duplicate:
https://github.com/darbyjohnston/DJV/issues/66

**Comment by SVAFnemesis** [comment]
> Hi, sorry about the memory caching, I hope to have it fixed in the next version. I already have an existing issue for that so I'm going to close this as a duplicate:
> #66

Thank you very much for addressing this issue, I appreciate the works being put into this amazing handy tool
