### ISSUE TITLE
djv 2.0.8 doesn't open

### ISSUE THREAD

**Issue by rophelan21** [darbyjohnston/DJV#424]
windows 10 version 20H2
build: 19042.985
AMD Ryzen Threadripper 2920X

Logs have no error that I can see.
Application runs, but does not display a window, even after minutes of waiting. 

version 1.3 of DJV_view.exe works fine.

[djv.log](https://github.com/darbyjohnston/DJV/files/6548173/djv.log)

**Comment by rophelan21** [comment]
Installed 2.0.7. Doesn't open either.
Installed 2.0.6 Bingo! It works fine.

**Comment by darbyjohnston** [comment]
Hi, and sorry for the delay! Could you try starting 2.0.8 again, and then sending me the log file? It should be located in your "Documents" directory, for example "Documents/DJV/djv.log".

Also what type of graphics card are you using?

**Comment by rophelan21** [comment]
I have three GTX 1080i cards in this system, which probably makes it an odd build.

Ok, so this may be frustrating, but as you can see I've installed 2.0.6, and things are working fine. 
I went back and installed 2.0.8 without uninstalling 2.0.6, and 2.0.8 seems to work fine now.  

I just uninstalled all versions:
Then installed 2.0.8 and it works fine. 

Something must have happened when installing 2.0.6 that fixed the installation of 2.0.8?


The original djv.log file is from the first installation of 2.0.8 where the window never opened, it just made that log. 
As I said, there are no errors in that log, but the GUI never drew, and you can see it exit without opening anything.

Sorry I can't be more help.

**Comment by rophelan21** [comment]
This is the current log file... but of course, everything is working fine. 

[djv.log](https://github.com/darbyjohnston/DJV/files/6581588/djv.log)

**Comment by darbyjohnston** [comment]
Thanks, I'm glad it's working now, though I'm not sure what caused the issue. The preferences should be specific to each version so I don't think that was it. If it happens again let me know, otherwise I'll close this issue.
