### ISSUE TITLE
append a sequence to another?

### ISSUE THREAD

**Issue by kybin** [darbyjohnston/DJV#433]
Hello. Is DVJ able to append a sequence to another?

Sometimes we want to see some nearby shots as a sequence.

Thanks!

**Comment by darbyjohnston** [comment]
Hi! Not currently, but I am writing a new playback engine that will support this using OpenTimelineIO. If you are interested here is a link:
https://github.com/darbyjohnston/tlRender

It's a separate project right now, but I hope to integrate it into DJV for the next release.

**Comment by kybin** [comment]
Oh, I see. I will check the project then. 

Thanks for the great work by the way!
