### ISSUE TITLE
Unsupported transform type !<BuiltinTransform> in OCIO profile

### ISSUE THREAD

**Issue by Festivize** [darbyjohnston/DJV#460]
Hi, I'm getting an error whenever I try to load Blender's OCIO configuration file.

`ERROR: Error: Loading the OCIO profile 'C:\Program Files\DJV2\etc\Color\blender\config.ocio' failed. Unsupported transform type !<BuiltinTransform> in OCIO profile. `

**Comment by Festivize** [comment]
It seems that the OCIO config for Blender was modified back in 3.1 and as a result,doesn't work with DJV now. Here's a band-aid fix which I don't know if it will affect the colors but here it is:

Replace

```
        - !<BuiltinTransform> {style: "UTILITY - ACES-AP0_to_CIE-XYZ-D65_BFD", direction: inverse} 
```

at line 103 with:

```
        - !<FileTransform> {src: xyz_D65_to_E.spimtx, interpolation: linear}
        - !<FileTransform> {src: xyz_to_aces.spimtx, interpolation: linear}
```

The files referenced in the latter are still present in the latest versions of Blender so it will work but I don't know if the colors will be affected.

**Comment by K1NG-rgi** [comment]
Alternatively, you can [reinstall blender 3.0.x](https://download.blender.org/release/Blender3.0/) and copy the OCIO config file from there. That way you won't interfere with your current blender version's colour management, and DJV will use a slightly outdated OCIO config file until this gets fixed!
