### ISSUE TITLE
DJV bugging out, green pixels everywhere.

### ISSUE THREAD

**Issue by RokiNoki** [darbyjohnston/DJV#479]
![image](https://user-images.githubusercontent.com/49653483/205044441-d80dcde4-c823-4181-8e71-7a2d9c87a2f7.png)

**Comment by darbyjohnston** [comment]
I haven't seen anything like that before, have you tried updating your graphic card drivers?

**Comment by RokiNoki** [comment]
It was indeed a driver issue, I have an RX580. Downgraded from 22.10.1 to 22.5.1 and works flawlessly!
