### ISSUE TITLE
Add export functionality

### ISSUE THREAD

**Issue by darbyjohnston** [darbyjohnston/DJV#64]
Original ticket:
https://sourceforge.net/p/djv/feature-requests/84/

**Comment by thomastraum** [comment]
I can see the export menu item and I checked documentation but I cant find out how to export a video

**Comment by darbyjohnston** [comment]
Hi, the export functionality has not been implemented yet, I need to remove the menu item until it is ready so there isn't any confusion.

**Comment by darbyjohnston** [comment]
I've decided to limit the scope of DJV and not include export functionality.
