### ISSUE TITLE
Timeline does not show frame numbers

### ISSUE THREAD

**Issue by darbyjohnston** [darbyjohnston/DJV#70]
Original ticket:
https://sourceforge.net/p/djv/feature-requests/90/

**Comment by darbyjohnston** [comment]
The timeline now shows frame number ticks and labels at appropriate intervals.

**Comment by donlencho** [comment]
Hi, Sorry to bring this up again, but I'm using DJV 2.0.5 and need to know what frame is displayed from an image sequence in DPX, and I cannot find where to get that info.
In this use case, it makes DJV not good for what I need so I would love to be able to know the frame number / file name (in case it's many images forming a sequence).
Maybe I'm just blind and don't look at the right place, in that case thanks for pointing it to me!

**Comment by darbyjohnston** [comment]
Hi, do you have the time units set to "frames"? You can change that in the settings (click the gear button in the top right):

![DJV Time Units Frames](https://user-images.githubusercontent.com/8532558/81240175-8b7b6e80-8fbb-11ea-891a-dd2147effe1a.PNG)

**Comment by donlencho** [comment]
Hi, no sorry, I had missed that, thanks for your reply, this is now working perfectly for my need!

**Comment by tiedave** [comment]
I had to google this to find out how to do it. 
It's in the right spot. Not sure where to put it where it's easier to see?

Thanks for having it searchable!
