### ISSUE TITLE
Add a grid overlay

### ISSUE THREAD

**Issue by darbyjohnston** [darbyjohnston/DJV#76]
Original ticket:
https://sourceforge.net/p/djv/feature-requests/96/

**Comment by aberkl** [comment]
High priority from my side.
- as suggested on another channel: I would love to see a coarse 8x8 (or 10x10) grid with chess-board coordinates ("check B3 for color fringes")
- I am frequently using the "1-pixel-grid" from DJV 1.3, please keep it! Very good to spot issues in
certain situations.

**Comment by darbyjohnston** [comment]
OK I've added this for the next version, along with the labels and controls for setting custom grid sizes; and yes, I agree the 1 pixel grid is quite useful!
![DJV Grid](https://user-images.githubusercontent.com/8532558/67257416-b13a8f00-f440-11e9-9c52-6330770e4c6e.PNG)
![DJV Grid 2](https://user-images.githubusercontent.com/8532558/67257420-b39ce900-f440-11e9-8551-e07796085600.PNG)

**Comment by aberkl** [comment]
After testing the grid in 2.0.5 I came to my (personal) conclusion that I would prefer a "chessboard" 8x8 notation rather than the square "X" and "Y" information:

	  A  B  C  D  E  F  G  H
	1
	2
	3
	4
	5
	6
	7
	8 

This takes up less space in the grid (1 character vs. 2) and imho is more intuitive, remember [Battleship](https://en.wikipedia.org/wiki/Battleship_(game))

**Comment by darbyjohnston** [comment]
What about the case for grids with more than 26 cells? Multiple letters? e.g., "AA", "AB", "AC", ..., "AAA", "AAB", "AAC"

**Comment by aberkl** [comment]
> What about the case for grids with more than 26 cells? Multiple letters? e.g., "AA", "AB", "AC", ..., "AAA", "AAB", "AAC"

I doubt that at least I will ever need such a detailed grid (with the exception of 1x1 as mentioned earlier). For me the grid is more a rough orientation to point someone to a certain region: "Check D9, there is a bad flare." So for me 8x8 would work perfectly up to and maybe beyond UHD resolution.
