### ISSUE TITLE
file path including characters like "üõöä" not working

### ISSUE THREAD

**Issue by porgand** [darbyjohnston/DJV#8]
error, when double-clicking on file, which path includes unicode characters (non-latin?), a la õäöü etc
drag and drop to player (from same location) works fine

it might be OS/filesystem naming issue
i'm on Win 10 pro

best regards,
Risto

**Comment by darbyjohnston** [comment]
Hi, thanks for the bug report; I'll add this to the list of fixes for the next version.

**Comment by darbyjohnston** [comment]
Hi, this should be fixed with the new version I just released, 1.3; give it a try and see if it works for you as well. You can download the new version here:
http://djv.sourceforge.net/Download.html

**Comment by porgand** [comment]
yes, it's fixed
thank you!

**Comment by darbyjohnston** [comment]
Great, thanks for testing it out!
