### ISSUE TITLE
when scrubbing timeline it starts skipping frames

### ISSUE THREAD

**Issue by darbyjohnston** [darbyjohnston/DJV#82]
Original ticket:
https://sourceforge.net/p/djv/feature-requests/102/

**Comment by ignasblazys** [comment]
Great news it's getting fixed! I am still using the old version because this single issue. Thank you!

**Comment by darbyjohnston** [comment]
This should be fixed with the new audio system.

**Comment by artintime** [comment]
Not fixed yet in 2.0.8 version
