### ISSUE TITLE
djv Core FileIO Cannot open

### ISSUE THREAD

**Issue by absconcept** [darbyjohnston/DJV#9]
[ERROR djv::Core::FileIO] Cannot open file: "P:\2019\Render\C0.tga"

Seems broken, can not load sequences of TGA,  or any other format for that matter, windows 10

Latest DJV installed, seems to be happening with older version too, this I think might be down to latest Windows 10 (V-1809 Build-17763.379)

https://ibb.co/d4PmH7J

**Comment by absconcept** [comment]
Found the problem, it was just down to the naming. It did not like:
C1-0001.tga

once I changed it to:

C-10001.tga

it worked fine :)

**Comment by oweissbarth** [comment]
I did some investigating.
I cannot open files with a "-" and a number on both sides of the "-".
For example:
1-1.jpg Doesn't work: ```[ERROR JPEG] Cannot open file
[ERROR] Cannot open image: /home/oliver/1.jpg```
a1-1.jpg Doesn't work: ```[ERROR JPEG] Cannot open file
[ERROR] Cannot open image: /home/oliver/a1.jpg```
1a-1.jpg works!
1-a1.jpg also works!

I've been testing on Linux with djv 1.3.0 and djv 2.0.2.
1.3.0 gives the error above while 2.0.2 fails silently.

Thanks for your awesome tool!

**Comment by oweissbarth** [comment]
I just checked 2.0.3 and this seems to be fixed. It's working now. Thank you very much.

**Comment by absconcept** [comment]
Filed for me, Tried this on windows 10 loading C-20000.TGA and it wont load the sequence.

**Comment by darbyjohnston** [comment]
oweissbarth: I was just going to suggest trying the new version since there are a number of fixes, happy to hear it works now!

absconcept: Sorry I haven't ported the TGA file reader to the new version, I'll get that in for the next version in a week or so. I also meed to add error messages so it's not so mysterious.

Darby

**Comment by absconcept** [comment]
New version looking great, very happy with such an amazing program, it has helped me loads with many 3D animation projects :)

**Comment by darbyjohnston** [comment]
New issue to track adding TGA and other file formats:
https://github.com/darbyjohnston/DJV/issues/63

**Comment by MiMEDesignStudio** [comment]
2.0.8 won't open at all. When I hover over the icon on the task bar just a white box appears in the preview popup.
